import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { NoticeToast } from "@/components/notice-toast";
import { formatDate, formatMoney } from "@/core/format";
import { requireModule } from "@/core/permissions/require-module";
import { getBankTransfer } from "@/modules/banking/bank-transfer-service";
import { BankingDocumentActions } from "@/modules/banking/banking-view-actions";

export default async function BankTransferViewPage({ params, searchParams }: { params: Promise<{ businessId: string; transferId: string }>; searchParams: Promise<{ notice?: string }> }) {
  const { businessId, transferId } = await params; const query = await searchParams; const { user, access } = await requireModule(businessId, "banking"); const record = getBankTransfer(businessId, user.id, transferId); if (!record) notFound(); const transfer = record.transfer; const status = String(transfer.document_status) as "posted" | "void"; const number = String(transfer.transfer_number);
  return <div className="page-container max-w-[950px]"><NoticeToast message={query.notice} /><Link href={`/b/${businessId}/banking/accounts/${String(transfer.from_bank_account_id)}`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> {String(transfer.from_account_name)}</Link><div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex items-center gap-2"><h1 className="page-title tabular">{number}</h1><Badge tone={status === "posted" ? "info" : "danger"}>{status === "posted" ? "Posted" : "Void"}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{formatDate(String(transfer.date))}</p><p className="money mt-3 text-xl font-semibold">{formatMoney(Number(transfer.amount_minor), access.business.currency)}</p></div><BankingDocumentActions businessId={businessId} kind="transfer" id={transferId} number={number} status={status} journalId={record.journals.find((j) => j.source_type === "bank_transfer")?.id} /></div><article className="rounded-lg border border-border bg-surface-raised p-5 sm:p-7"><div className="grid items-center gap-4 rounded-md bg-surface p-4 sm:grid-cols-[1fr_auto_1fr]"><div><p className="text-xs text-muted-foreground">From</p><Link href={`/b/${businessId}/banking/accounts/${String(transfer.from_bank_account_id)}`} className="mt-1 block font-semibold text-primary hover:underline">{String(transfer.from_account_name)}</Link></div><ArrowRight className="hidden size-5 text-muted-foreground sm:block" /><div><p className="text-xs text-muted-foreground">To</p><Link href={`/b/${businessId}/banking/accounts/${String(transfer.to_bank_account_id)}`} className="mt-1 block font-semibold text-primary hover:underline">{String(transfer.to_account_name)}</Link></div></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Reference</dt><dd className="mt-1">{String(transfer.reference ?? "—")}</dd></div><div><dt className="text-xs text-muted-foreground">Description</dt><dd className="mt-1">{String(transfer.description ?? "—")}</dd></div></dl><section className="mt-6 border-t border-border pt-5"><h2 className="text-sm font-semibold">Generated journal</h2><div className="mt-3 flex flex-wrap gap-3">{record.journals.map((journal) => <Link key={journal.id} href={`/b/${businessId}/accounting/journal/${journal.id}`} className="rounded-md border border-border bg-surface px-3 py-2 text-sm font-medium text-primary hover:underline">{journal.source_type === "bank_transfer" ? "Original" : "Reversal"}: {journal.entry_number}</Link>)}</div></section></article></div>;
}
