import Link from "next/link";
import { ArrowLeft, Braces } from "lucide-react";
import { notFound } from "next/navigation";
import { NoticeToast } from "@/components/notice-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireModule } from "@/core/permissions/require-module";
import { formatDate, formatMoney } from "@/core/format";
import { quantityMicrosToInput, rateBasisPointsToPercent } from "@/modules/accounting/calculations/money";
import {
  InboundLineMappingControls,
  InboundReviewActions,
  ProcurementMatchControls,
  SupplierResolutionControls,
} from "@/modules/inbound-einvoicing/inbound-controls";
import { getInboundEInvoice } from "@/modules/inbound-einvoicing/inbound-service";

const labels: Record<string, string> = {
  NeedsSupplier: "Needs Supplier", NeedsReview: "Needs Review", ReadyForDraft: "Ready for Draft",
  DraftCreated: "Draft Created", ValidationFailed: "Validation Failed", Processed: "Processed",
  Rejected: "Rejected", Archived: "Archived", Received: "Received", Validated: "Validated",
};
const tones: Record<string, "neutral" | "info" | "warning" | "success" | "danger"> = {
  NeedsSupplier: "warning", NeedsReview: "warning", ReadyForDraft: "success", DraftCreated: "info",
  ValidationFailed: "danger", Processed: "success", Rejected: "danger", Archived: "neutral",
  Received: "info", Validated: "info",
};

export default async function SupplierEInvoiceDetailPage({
  params,
  searchParams,
}: {
  params: Promise<{ businessId: string; id: string }>;
  searchParams: Promise<{ notice?: string }>;
}) {
  const { businessId, id } = await params;
  const { notice } = await searchParams;
  const { user, access } = await requireModule(businessId, "purchases");
  const record = getInboundEInvoice(businessId, user.id, id);
  if (!record) notFound();
  const officialValid = Boolean(record.validation?.layers.pintUbl.valid && record.validation.layers.pintAe.valid && record.validation.layers.parsing.valid);
  const purchaseOrderLines = record.comparison.map((line) => ({ id: String(line.purchase_order_line_id), label: `${Number(line.position) + 1} · ${String(line.description)}` }));
  const itemOptions = record.options.items.map((item) => ({ id: String(item.id), label: `${item.sku ? `${item.sku} · ` : ""}${String(item.name)}` }));
  const accountOptions = record.options.expenseAccounts.map((account) => ({ id: account.id, label: `${account.code} · ${account.name}` }));
  const taxOptions = record.options.taxCodes.map((tax) => ({ id: String(tax.id), label: `${String(tax.name)} (${rateBasisPointsToPercent(Number(tax.rate_basis_points))}%)` }));
  const projectOptions = record.options.projects.map((project) => ({ id: project.id, label: `${project.code} · ${project.name}` }));
  return <div className="page-container max-w-[1320px]">
    <NoticeToast message={notice} />
    <Link href={`/b/${businessId}/purchases/einvoices`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Supplier eInvoices</Link>
    <div className="page-header"><div><div className="flex flex-wrap items-center gap-2"><h1 className="page-title tabular">{record.documentNumber}</h1><Badge tone={tones[record.status] ?? "neutral"}>{labels[record.status] ?? record.status}</Badge><Badge tone="info">MOCK</Badge>{officialValid && <Badge tone="success">PINT-AE Valid</Badge>}</div><p className="page-description">{record.sellerLegalName} · {record.documentType === "credit_note" ? "Credit Note" : "Invoice"} · Received {formatDate(record.receivedAt.slice(0, 10))}</p></div>{record.purchaseInvoice && <Button asChild><Link href={`/b/${businessId}/purchases/invoices/${record.purchaseInvoice.id}`}>View {String(record.purchaseInvoice.internal_number)}</Link></Button>}</div>
    {record.lastError && <div className={`mb-5 rounded-md border px-4 py-3 text-sm ${record.status === "Rejected" || record.status === "ValidationFailed" ? "border-danger/25 bg-danger/5 text-danger" : "border-warning/25 bg-warning/5 text-warning"}`}>{record.lastError}{record.duplicatePurchaseInvoice && <Link href={`/b/${businessId}/purchases/invoices/${record.duplicatePurchaseInvoice.id}`} className="ml-2 font-medium underline">View {String(record.duplicatePurchaseInvoice.internal_number)}</Link>}{record.duplicateOfId && <Link href={`/b/${businessId}/purchases/einvoices/${record.duplicateOfId}`} className="ml-2 font-medium underline">View earlier inbound document</Link>}</div>}
    {record.documentType === "credit_note" && <div className="mb-5 rounded-md border border-info/25 bg-info/5 px-4 py-3 text-sm"><strong>Valid electronic credit note — accounting conversion not yet supported.</strong><span className="mt-1 block text-muted-foreground">Source invoice reference: {record.sourceInvoiceReference ?? "Not supplied"}. No negative Purchase Invoice workaround is created.</span></div>}

    <section className="mb-5 rounded-lg border border-border bg-surface-raised p-5">
      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><dl className="space-y-2 text-sm"><div><dt className="text-xs text-muted-foreground">Supplier identity</dt><dd className="mt-1 font-medium">{record.sellerLegalName}</dd></div><div><dt className="text-xs text-muted-foreground">Endpoint</dt><dd className="mt-1 tabular">{record.sellerEndpointScheme && record.sellerEndpointId ? `${record.sellerEndpointScheme}:${record.sellerEndpointId}` : "Not supplied"}</dd></div><div><dt className="text-xs text-muted-foreground">TRN</dt><dd className="mt-1 tabular">{record.sellerTrn ?? "Not supplied"}</dd></div></dl><dl className="space-y-2 text-sm"><div><dt className="text-xs text-muted-foreground">Issue date</dt><dd className="mt-1">{formatDate(record.issueDate)}</dd></div><div><dt className="text-xs text-muted-foreground">VAT tax date</dt><dd className="mt-1">{record.taxDate ? formatDate(record.taxDate) : formatDate(record.issueDate)}</dd></div><div><dt className="text-xs text-muted-foreground">Due date</dt><dd className="mt-1">{record.dueDate ? formatDate(record.dueDate) : "Not supplied"}</dd></div></dl><dl className="space-y-2 text-sm"><div><dt className="text-xs text-muted-foreground">UUID</dt><dd className="mt-1 break-all font-mono text-xs">{record.documentUuid}</dd></div><div><dt className="text-xs text-muted-foreground">Specification</dt><dd className="mt-1">PINT-AE {record.specificationVersion}</dd></div><div><dt className="text-xs text-muted-foreground">Buyer identity</dt><dd className="mt-1">{record.buyerIdentityVerified ? "Verified server-side" : "Not verified"}</dd></div></dl><dl className="space-y-2 text-sm"><div><dt className="text-xs text-muted-foreground">Net</dt><dd className="money mt-1">{formatMoney(record.subtotalMinor, record.currencyCode)}</dd></div><div><dt className="text-xs text-muted-foreground">VAT</dt><dd className="money mt-1">{formatMoney(record.taxMinor, record.currencyCode)}</dd></div><div><dt className="text-xs text-muted-foreground">Total / due</dt><dd className="money mt-1 font-semibold">{formatMoney(record.totalMinor, record.currencyCode)} / {formatMoney(record.amountDueMinor, record.currencyCode)}</dd></div></dl></div>
    </section>

    <div className="grid gap-5 lg:grid-cols-[0.85fr_1.15fr]">
      <section className="rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Supplier matching</h2><p className="mt-1 text-sm text-muted-foreground">Priority: endpoint + scheme, TRN, legal registration, confirmed mapping, then manual selection. Name-only matching is never automatic.</p><div className="mt-4">{record.supplier ? <div className="rounded-md border border-success/25 bg-success/5 p-3 text-sm"><p className="font-medium">Confirmed: {String(record.supplier.name)}</p><p className="mt-1 text-xs text-muted-foreground">Strong identities can be retained in the Supplier mapping registry.</p></div> : <SupplierResolutionControls businessId={businessId} documentId={record.id} suppliers={record.options.suppliers.map((supplier) => ({ id: supplier.id, label: supplier.name }))} />}</div></section>
      <section className="rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">PO / Goods Receipt matching</h2><p className="mt-1 text-sm text-muted-foreground">Explicit references are checked first; documents belonging to another Supplier are rejected.</p><div className="mt-4">{record.supplierId ? <ProcurementMatchControls businessId={businessId} documentId={record.id} supplierId={record.supplierId} purchaseOrderId={record.purchaseOrderId} goodsReceiptId={record.goodsReceiptId} purchaseOrders={record.options.purchaseOrders.map((order) => ({ id: String(order.id), label: `${String(order.order_number)} · ${String(order.status)}`, supplierId: String(order.supplier_id) }))} goodsReceipts={record.options.goodsReceipts.map((receipt) => ({ id: String(receipt.id), label: String(receipt.receipt_number), supplierId: String(receipt.supplier_id), purchaseOrderId: receipt.purchase_order_id ? String(receipt.purchase_order_id) : null }))} /> : <p className="text-sm text-muted-foreground">Confirm the Supplier first.</p>}</div></section>
    </div>

    {record.comparison.length > 0 && <section className="data-panel mt-5"><div className="border-b border-border px-4 py-3"><h2 className="font-semibold">Purchase Order comparison</h2><p className="mt-1 text-xs text-muted-foreground">Ordered, posted received quantity, prior non-void invoicing, current eInvoice, and variance.</p></div><div className="overflow-x-auto"><table className="data-table min-w-[780px]"><thead><tr><th>PO line</th><th className="text-right!">Ordered</th><th className="text-right!">Received</th><th className="text-right!">Previously invoiced</th><th className="text-right!">Current eInvoice</th><th className="text-right!">Variance to ordered</th></tr></thead><tbody>{record.comparison.map((line) => { const variance = Number(line.ordered_micros) - Number(line.previously_invoiced_micros) - Number(line.current_invoice_micros); return <tr key={String(line.purchase_order_line_id)}><td>{String(line.description)}</td><td className="money text-right">{quantityMicrosToInput(Number(line.ordered_micros))}</td><td className="money text-right">{quantityMicrosToInput(Number(line.received_micros))}</td><td className="money text-right">{quantityMicrosToInput(Number(line.previously_invoiced_micros))}</td><td className="money text-right">{quantityMicrosToInput(Number(line.current_invoice_micros))}</td><td className="money text-right">{quantityMicrosToInput(Math.abs(variance))}{variance < 0 ? " over" : variance > 0 ? " remaining" : ""}</td></tr>; })}</tbody></table></div></section>}

    <section className="mt-5 rounded-lg border border-border bg-surface-raised p-5"><div><h2 className="text-base font-semibold">Lines and mappings</h2><p className="mt-1 text-sm text-muted-foreground">Source quantities, prices, net, and VAT are immutable. Confirm ERP item/expense, Project, VAT, and any PO line mapping.</p></div><div className="mt-4 space-y-3">{record.lines.map((line) => <article key={line.id} className="rounded-md border border-border p-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto_auto_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{line.item_name || line.description}</p><Badge tone={line.match_status === "Matched" ? "success" : line.match_status === "Possible Match" ? "warning" : "neutral"}>{line.match_status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Source line {line.source_line_id}{line.supplier_item_identifier ? ` · Supplier item ${line.supplier_item_identifier}` : ""}{line.order_line_reference ? ` · PO line ref ${line.order_line_reference}` : ""}</p></div><div className="text-right text-sm"><p className="text-xs text-muted-foreground">Quantity</p><p className="money mt-1">{quantityMicrosToInput(line.quantity_micros)} {line.unit_code}</p></div><div className="text-right text-sm"><p className="text-xs text-muted-foreground">Unit price</p><p className="money mt-1">{formatMoney(line.unit_price_minor, record.currencyCode)}</p></div><div className="text-right text-sm"><p className="text-xs text-muted-foreground">Net / VAT / Gross</p><p className="money mt-1">{formatMoney(line.net_amount_minor, record.currencyCode)} / {formatMoney(line.tax_amount_minor, record.currencyCode)} / {formatMoney(line.gross_amount_minor, record.currencyCode)}</p><p className="mt-1 text-xs text-muted-foreground">{line.tax_category} · {rateBasisPointsToPercent(line.tax_rate_basis_points)}%</p></div></div>{record.supplierId && !["DraftCreated", "Processed", "Rejected", "Archived", "ValidationFailed"].includes(record.status) && <InboundLineMappingControls businessId={businessId} documentId={record.id} line={{ id: line.id, purchaseOrderLineId: line.purchase_order_line_id, itemId: line.item_id, expenseAccountId: line.expense_account_id, taxCodeId: line.tax_code_id, projectId: line.project_id, supplierItemIdentifier: line.supplier_item_identifier }} purchaseOrderLines={purchaseOrderLines} items={itemOptions} expenseAccounts={accountOptions} taxCodes={taxOptions} projects={projectOptions} />}</article>)}</div></section>

    <section className="mt-5 rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Validation</h2><div className="mt-3 grid gap-2 sm:grid-cols-3">{record.validation && Object.entries(record.validation.layers).map(([name, layer]) => <div key={name} className="rounded-md border border-border p-3"><p className="text-xs capitalize text-muted-foreground">{name.replace(/([A-Z])/g, " $1")}</p><p className={`mt-1 text-sm font-medium ${layer.valid ? "text-success" : "text-danger"}`}>{layer.valid ? "Passed" : `${layer.issueCount} issue(s)`}</p></div>)}</div>{record.validation?.issues.length ? <ul className="mt-4 space-y-2">{record.validation.issues.map((issue, index) => <li key={`${issue.ruleId}-${index}`} className="rounded-md border border-danger/20 bg-danger/5 px-3 py-2 text-sm"><span className="font-mono text-xs">{issue.ruleId}</span> · {issue.message}</li>)}</ul> : <p className="mt-4 text-sm text-success">No validation findings.</p>}</section>

    <section className="mt-5 rounded-lg border border-border bg-surface-raised p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold">Source XML</h2><p className="mt-1 text-sm text-muted-foreground">Original XML is hidden by default, downloaded as XML, and never rendered as HTML.</p></div><Button asChild size="sm" variant="secondary"><a href={`/api/businesses/${businessId}/purchases/einvoices/${record.id}/xml`}><Braces className="size-4" /> Download original XML</a></Button></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">SHA-256</dt><dd className="mt-1 break-all font-mono text-xs">{record.rawHash}</dd></div><div><dt className="text-xs text-muted-foreground">Provider boundary</dt><dd className="mt-1">MOCK · {record.networkStatus ?? "Received"}</dd></div></dl></section>

    <section className="mt-5 rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">History</h2><div className="mt-3 overflow-x-auto"><table className="data-table min-w-[650px]"><thead><tr><th>Time</th><th>Event</th><th>Status</th><th>Provider</th></tr></thead><tbody>{record.events.map((event) => <tr key={String(event.id)}><td>{formatDate(String(event.created_at).slice(0, 10))}<span className="ml-2 text-xs text-muted-foreground">{String(event.created_at).slice(11, 19)}</span></td><td>{String(event.event_type)}</td><td>{String(event.status)}</td><td><Badge tone="info">{String(event.provider_key).toUpperCase()}</Badge></td></tr>)}</tbody></table></div></section>

    <section className="mt-5 rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Review action</h2><p className="mt-1 text-sm text-muted-foreground">Draft creation has no journal, AP, VAT, or stock effect. Posting remains a separate action on the normal Purchase Invoice page.</p><div className="mt-4"><InboundReviewActions businessId={businessId} documentId={record.id} status={record.status} duplicateKind={record.duplicateKind} isAdministrator={access.membership.role === "administrator"} /></div></section>
  </div>;
}
