import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { requireModule } from "@/core/permissions/require-module";
import { SupplierForm } from "@/modules/suppliers/supplier-form";
import { getSupplier } from "@/modules/suppliers/supplier-service";
import { getCurrencySettings } from "@/modules/currency/exchange-rate";

export default async function EditSupplierPage({ params }: { params: Promise<{ businessId: string; supplierId: string }> }) { const { businessId, supplierId } = await params; const { user } = await requireModule(businessId, "purchases"); const supplier = getSupplier(businessId, user.id, supplierId); if (!supplier) notFound(); const settings = getCurrencySettings(businessId, user.id); return <div className="page-container max-w-[900px]"><Link href={`/b/${businessId}/suppliers/${supplierId}`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> {supplier.name}</Link><div className="mb-7"><h1 className="page-title">Edit Supplier</h1><p className="page-description">Update contact, tax, address, and status details.</p></div><SupplierForm businessId={businessId} supplierId={supplierId} currencies={settings.currencies.filter((currency) => currency.is_active || currency.code === supplier.defaultCurrencyCode).map((currency) => ({ code: currency.code, name: currency.name }))} initial={{ name: supplier.name, email: supplier.email ?? "", phone: supplier.phone ?? "", taxReference: supplier.taxReference ?? "", address: supplier.address ?? "", legalName: supplier.legalName ?? "", trn: supplier.trn ?? "", legalRegistrationIdentifier: supplier.legalRegistrationIdentifier ?? "", electronicAddress: supplier.electronicAddress ?? "", electronicAddressScheme: supplier.electronicAddressScheme ?? "", registeredAddress: supplier.registeredAddress ?? "", countryCode: supplier.countryCode ?? "", notes: supplier.notes ?? "", isActive: supplier.isActive, defaultCurrencyCode: supplier.defaultCurrencyCode }} /></div>; }
