"use client";
import { useRouter } from "next/navigation";
import { FormError } from "@/components/form-error";
import { useMemo, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { Columns3, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { useFieldArray, useForm, useWatch } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatMoney } from "@/core/format";
import { parseCurrencyAmountToMinor } from "@/modules/currency/conversion";
import { calculateTax, multiplyMoneyByQuantity, parseQuantityToMicros } from "@/modules/accounting/calculations/money";
import { saveCreditNoteAction } from "./actions";
import { creditNoteInputSchema, type CreditNoteInput } from "./credit-note-input";
import type { CreditNoteStatus } from "./credit-note-service";
import { emirateLabels, emirates } from "@/modules/tax/uae-vat-config";
import { creditNoteReasonCodes } from "@/modules/einvoicing/einvoice-types";
import { DocumentFormFooter } from "@/components/document-form-footer";
import { SelectNative } from "@/components/ui/select-native";

type Option = { id: string; name: string }; type AccountOption = { id: string; code: string; name: string }; type TaxOption = { id: string; name: string; rateBasisPoints: number }; type InvoiceOption = { id: string; invoiceNumber: string; customerId: string; balanceMinor: number; currencyCode: string; minorUnit: number; exchangeRateToBase: string; exchangeRateDate: string; exchangeRateSource: string }; type ProjectOption = { id: string; code: string; name: string; customerId: string | null };

function previewLine(line: CreditNoteInput["lines"][number] | undefined, taxCodes: TaxOption[], minorUnit: number) {
  try {
    const unitPriceMinor = parseCurrencyAmountToMinor(String(line?.unitPrice || "0"), minorUnit, "Unit price");
    const quantityMicros = parseQuantityToMicros(String(line?.quantity || "0"));
    const netMinor = multiplyMoneyByQuantity(unitPriceMinor, quantityMicros);
    const rate = taxCodes.find((tax) => tax.id === line?.taxCodeId)?.rateBasisPoints ?? 0;
    const taxMinor = calculateTax(netMinor, rate);
    return { netMinor, taxMinor, grossMinor: netMinor + taxMinor };
  } catch { return { netMinor: 0, taxMinor: 0, grossMinor: 0 }; }
}
export function CreditNoteForm({ businessId, noteId, documentStatus = "draft", customers, invoices, salesAccounts, taxCodes, projects, currency, initial }: { businessId: string; noteId?: string; documentStatus?: CreditNoteStatus; customers: Option[]; invoices: InvoiceOption[]; salesAccounts: AccountOption[]; taxCodes: TaxOption[]; projects: ProjectOption[]; currency: string; initial: CreditNoteInput }) {
  const router = useRouter();
  const [serverError, setServerError] = useState(""); const [showLineProjects, setShowLineProjects] = useState(() => initial.lines.some((line) => Boolean(line.projectId))); const form = useForm<CreditNoteInput>({ resolver: zodResolver(creditNoteInputSchema), defaultValues: initial }); const { register, control, handleSubmit, setError, setValue, formState: { errors, isSubmitting } } = form; const { fields, append, remove } = useFieldArray({ control, name: "lines" });
  const customerId = useWatch({ control, name: "customerId" }); const invoiceId = useWatch({ control, name: "sourceInvoiceId" }); const lines = useWatch({ control, name: "lines" }) ?? []; const eligibleInvoices = useMemo(() => invoices.filter((invoice) => invoice.customerId === customerId), [customerId, invoices]); const eligibleProjects = useMemo(() => projects.filter((project) => !project.customerId || project.customerId === customerId), [customerId, projects]); const selected = invoices.find((invoice) => invoice.id === invoiceId);
  const currencyCode = useWatch({ control, name: "currencyCode" }) || selected?.currencyCode || currency; const exchangeRateToBase = useWatch({ control, name: "exchangeRateToBase" }) || selected?.exchangeRateToBase || "1"; const exchangeRateDate = useWatch({ control, name: "exchangeRateDate" }) || selected?.exchangeRateDate || ""; const exchangeRateSource = useWatch({ control, name: "exchangeRateSource" }) || selected?.exchangeRateSource || "Base"; const minorUnit = selected?.minorUnit ?? 2;
  const previews = lines.map((line) => previewLine(line, taxCodes, minorUnit)); const subtotalMinor = previews.reduce((sum, row) => sum + row.netMinor, 0); const taxMinor = previews.reduce((sum, row) => sum + row.taxMinor, 0); const defaultSales = salesAccounts[0]?.id ?? ""; const defaultTax = taxCodes.find((item) => item.rateBasisPoints === 500)?.id ?? taxCodes[0]?.id ?? "";
  async function save(values: CreditNoteInput, intent: "draft" | "post") { setServerError(""); const result = await saveCreditNoteAction(businessId, noteId ?? null, values, intent); if (result.fieldErrors) for (const [field, messages] of Object.entries(result.fieldErrors)) setError(field as keyof CreditNoteInput, { message: messages[0] }); if (result.error) setServerError(result.error); }
  const cancelHref = noteId ? `/b/${businessId}/sales/credit-notes/${noteId}` : `/b/${businessId}/sales/credit-notes`;
  return <form className="space-y-7 max-w-4xl" noValidate>{serverError && <FormError message={serverError} />}<section className="border-b border-border pb-7"><h2 className="text-base font-semibold">Credit details</h2><p className="mt-1 text-sm text-muted-foreground">A posted credit reverses Sales and output VAT while reducing Accounts Receivable.</p><div className="mt-5 grid gap-5 md:grid-cols-3">
    <div className="space-y-1.5"><Label htmlFor="customerId">Customer</Label><SelectNative id="customerId"  {...register("customerId", { onChange: () => setValue("sourceInvoiceId", "") })} aria-invalid={!!errors.customerId}><option value="">Choose a customer…</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</SelectNative>{errors.customerId && <p className="field-error">{errors.customerId.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="sourceInvoiceId">Apply to invoice</Label><SelectNative id="sourceInvoiceId"  {...register("sourceInvoiceId", { onChange: (event) => { const invoice = invoices.find((entry) => entry.id === event.target.value); if (!invoice) return; setValue("currencyCode", invoice.currencyCode); setValue("exchangeRateToBase", invoice.exchangeRateToBase); setValue("exchangeRateDate", invoice.exchangeRateDate); setValue("exchangeRateSource", invoice.exchangeRateSource as "Base" | "Manual" | "CBUAE"); } })} aria-invalid={!!errors.sourceInvoiceId}><option value="">Choose a posted invoice…</option>{eligibleInvoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.invoiceNumber} · {formatMoney(invoice.balanceMinor, invoice.currencyCode, invoice.minorUnit)} remaining</option>)}</SelectNative>{selected && <p className="text-xs text-muted-foreground">Maximum credit {formatMoney(selected.balanceMinor, selected.currencyCode, selected.minorUnit)}</p>}{errors.sourceInvoiceId && <p className="field-error">{errors.sourceInvoiceId.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="date">Credit note date</Label><Input id="date" type="date" {...register("date")} aria-invalid={!!errors.date} />{errors.date && <p className="field-error">{errors.date.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="taxDate">VAT tax date</Label><Input id="taxDate" type="date" {...register("taxDate")} aria-invalid={!!errors.taxDate} />{errors.taxDate && <p className="field-error">{errors.taxDate.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="supplyEmirate">Supply Emirate</Label><SelectNative id="supplyEmirate"  {...register("supplyEmirate")}><option value="">Use business default</option>{emirates.map((emirate) => <option key={emirate} value={emirate}>{emirateLabels[emirate]}</option>)}</SelectNative></div>
    <div className="space-y-1.5"><Label htmlFor="projectId">Project <span className="font-normal text-muted-foreground">(optional)</span></Label><SelectNative id="projectId"  {...register("projectId")}><option value="">No project</option>{eligibleProjects.map((project) => <option key={project.id} value={project.id}>{project.code} — {project.name}</option>)}</SelectNative></div>
    <div className="space-y-1.5"><Label htmlFor="reference">Reference <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="reference" {...register("reference")} /></div><div className="space-y-1.5 md:col-span-2"><Label htmlFor="reason">Reason <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="reason" {...register("reason")} /></div>
    <div className="space-y-1.5 md:col-span-2"><Label htmlFor="eInvoiceReasonCode">PINT-AE credit reason</Label><SelectNative id="eInvoiceReasonCode"  {...register("eInvoiceReasonCode")}><option value="">Choose before eInvoice preparation</option>{creditNoteReasonCodes.map((reason) => <option key={reason.value} value={reason.value}>{reason.value} · {reason.label}</option>)}</SelectNative></div>
  </div></section>
  <section className="border-b border-border pb-7"><h2 className="text-base font-semibold">Inherited currency snapshot</h2><p className="mt-1 text-sm text-muted-foreground">A Credit Note always uses the linked invoice currency and original rate, so the correction does not manufacture an FX difference.</p><dl className="mt-4 grid gap-3 rounded-lg border border-border bg-surface-raised p-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-muted-foreground">Currency</dt><dd className="mt-1 font-mono font-semibold">{currencyCode}</dd></div><div><dt className="text-xs text-muted-foreground">Rate</dt><dd className="money mt-1">1 {currencyCode} = {exchangeRateToBase} {currency}</dd></div><div><dt className="text-xs text-muted-foreground">Rate date</dt><dd className="mt-1">{exchangeRateDate || "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Source</dt><dd className="mt-1">{exchangeRateSource}</dd></div></dl></section>
  <details className="rounded-lg border border-border bg-surface-raised"><summary className="cursor-pointer px-4 py-3 text-sm font-semibold">Advanced Electronic Invoicing transaction types</summary><div className="grid gap-3 border-t border-border p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.freeTradeZone")} /> Free Trade Zone</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.deemedSupply")} /> Deemed supply</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.marginScheme")} /> Margin scheme</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.summaryInvoice")} /> Summary invoice</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.continuousSupply")} /> Continuous supply</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.agentBilling")} /> Agent billing</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.eCommerce")} /> E-commerce</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...register("eInvoiceTransactionFlags.export")} /> Export</label></div></details>
  <section><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-base font-semibold">Credited items</h2><p className="mt-1 text-sm text-muted-foreground">Use the original revenue, VAT, and Project allocations for a clean reversal.</p></div><div className="flex gap-2"><Button type="button" variant="ghost" size="sm" onClick={() => setShowLineProjects((value) => !value)} aria-pressed={showLineProjects}><Columns3 className="size-4" /> {showLineProjects ? "Hide line Projects" : "Show Project per line"}</Button><Button type="button" variant="secondary" size="sm" onClick={() => append({ description: "", quantity: "1", unitPrice: "0.00", salesAccountId: defaultSales, taxCodeId: defaultTax, projectId: "" })}><Plus className="size-4" /> Add line</Button></div></div>
    {typeof errors.lines?.message === "string" && <p className="field-error mb-2">{errors.lines.message}</p>}<div className="overflow-x-auto rounded-lg border border-border bg-surface-raised"><table className={`data-table ${showLineProjects ? "min-w-[1240px]" : "min-w-[1040px]"}`}><thead><tr><th className="min-w-[260px]">Description</th><th className="w-24 text-right!">Qty</th><th className="w-32 text-right!">Rate</th><th className="w-52">Sales account</th><th className="w-40">VAT</th>{showLineProjects && <th className="w-52">Project override</th>}<th className="w-32 text-right!">Amount</th><th className="w-12"><span className="sr-only">Remove</span></th></tr></thead><tbody>{fields.map((field, index) => <tr key={field.id} className="hover:bg-transparent!"><td><Input aria-label={`Line ${index + 1} description`} {...register(`lines.${index}.description`)} />{errors.lines?.[index]?.description && <p className="field-error">{errors.lines[index]?.description?.message}</p>}</td><td><Input className="money text-right" type="number" min="0.0001" step="0.0001" aria-label={`Line ${index + 1} quantity`} {...register(`lines.${index}.quantity`)} /></td><td><Input className="money text-right" type="number" min="0" step="0.000001" aria-label={`Line ${index + 1} rate`} {...register(`lines.${index}.unitPrice`)} /></td><td><SelectNative  aria-label={`Line ${index + 1} sales account`} {...register(`lines.${index}.salesAccountId`)}>{salesAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} {account.name}</option>)}</SelectNative></td><td><SelectNative  aria-label={`Line ${index + 1} tax code`} {...register(`lines.${index}.taxCodeId`)}>{taxCodes.map((taxCode) => <option key={taxCode.id} value={taxCode.id}>{taxCode.name}</option>)}</SelectNative></td>{showLineProjects && <td><SelectNative  aria-label={`Line ${index + 1} project override`} {...register(`lines.${index}.projectId`)}><option value="">Use document Project</option>{eligibleProjects.map((project) => <option key={project.id} value={project.id}>{project.code} — {project.name}</option>)}</SelectNative></td>}<td className="money text-right">{formatMoney(previews[index]?.grossMinor ?? 0, currencyCode, minorUnit)}</td><td><Button type="button" size="icon" variant="ghost" aria-label={`Remove line ${index + 1}`} disabled={fields.length === 1} title={fields.length === 1 ? "A credit note needs at least one line" : undefined} onClick={() => remove(index)}><Trash2 className="size-4 text-muted-foreground" /></Button></td></tr>)}</tbody></table></div>
    <dl className="mt-5 ml-auto w-full max-w-xs space-y-2 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Subtotal</dt><dd className="money">{formatMoney(subtotalMinor, currencyCode, minorUnit)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">VAT</dt><dd className="money">{formatMoney(taxMinor, currencyCode, minorUnit)}</dd></div><div className="flex justify-between border-t border-border pt-2 text-base font-semibold"><dt>Total credit</dt><dd className="money">{formatMoney(subtotalMinor + taxMinor, currencyCode, minorUnit)}</dd></div></dl>
  </section><DocumentFormFooter onCancel={() => router.push(cancelHref)}>{documentStatus === "posted" ? <Button type="button" disabled={isSubmitting} onClick={handleSubmit((values) => save(values, "post"))}>{isSubmitting && <LoaderCircle className="size-4 animate-spin" />} Update Posted Credit</Button> : <div className="flex gap-2"><Button type="button" variant="secondary" disabled={isSubmitting} onClick={handleSubmit((values) => save(values, "draft"))}>Save Draft</Button><Button type="button" disabled={isSubmitting} onClick={handleSubmit((values) => save(values, "post"))}>{isSubmitting && <LoaderCircle className="size-4 animate-spin" />} Post Credit Note</Button></div>}</DocumentFormFooter>
    </form>;
}
