import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { requireModule } from "@/core/permissions/require-module";
import { formatMoney } from "@/core/format";
import { listCustomers } from "@/modules/customers/customer-service";
import { ProjectStatusBadge } from "@/modules/projects/project-status";
import { getProjectProfitability } from "@/modules/projects/project-view-service";

const selectClass = "mt-1 block h-9 min-w-44 rounded-[6px] border border-border-strong bg-surface-raised px-3 text-sm text-foreground outline-none focus:border-primary focus:ring-2 focus:ring-ring/25";

export default async function ProjectProfitabilityPage({ params, searchParams }: { params: Promise<{ businessId: string }>; searchParams: Promise<{ dateFrom?: string; dateTo?: string; status?: string; customerId?: string }> }) {
  const { businessId } = await params;
  const filters = await searchParams;
  const { user, access } = await requireModule(businessId, "reports");
  const customers = listCustomers(businessId, user.id);
  const rows = getProjectProfitability(businessId, user.id, filters);
  const totals = rows.reduce((sum, row) => ({ revenue: sum.revenue + row.revenue_minor, cost: sum.cost + row.cost_minor }), { revenue: 0, cost: 0 });
  return <div className="page-container max-w-[1150px]"><Link href={`/b/${businessId}/reports`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Reports</Link><div className="page-header"><div><h1 className="page-title">Project Profitability</h1><p className="page-description">Revenue and cost from posted Income and Expense journal lines tagged to Projects.</p></div></div><form className="mb-4 flex flex-wrap items-end gap-3 rounded-lg border border-border bg-surface p-3"><label className="space-y-1 text-xs text-muted-foreground">Date from<Input name="dateFrom" type="date" defaultValue={filters.dateFrom} className="mt-1 w-40 text-foreground" /></label><label className="space-y-1 text-xs text-muted-foreground">Date to<Input name="dateTo" type="date" defaultValue={filters.dateTo} className="mt-1 w-40 text-foreground" /></label><label className="space-y-1 text-xs text-muted-foreground">Status<select name="status" defaultValue={filters.status ?? ""} className={selectClass}><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="on_hold">On Hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="space-y-1 text-xs text-muted-foreground">Customer<select name="customerId" defaultValue={filters.customerId ?? ""} className={selectClass}><option value="">All customers</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><Button type="submit" variant="secondary">Apply</Button></form>
    {rows.length ? <div className="data-panel overflow-x-auto"><table className="data-table min-w-[850px]"><thead><tr><th>Project</th><th>Customer</th><th>Status</th><th className="text-right!">Revenue</th><th className="text-right!">Cost</th><th className="text-right!">Gross Profit</th><th className="text-right!">Margin %</th></tr></thead><tbody>{rows.map((row) => { const profit = row.revenue_minor - row.cost_minor; const margin = row.revenue_minor ? (profit / row.revenue_minor) * 100 : null; return <tr key={row.id}><td><Link href={`/b/${businessId}/projects/${row.id}`} className="font-medium text-primary hover:underline"><span className="tabular">{row.code}</span><span className="ml-2 text-foreground">{row.name}</span></Link></td><td>{row.customer_name ?? "—"}</td><td><ProjectStatusBadge status={row.status} /></td><td className="money text-right">{formatMoney(row.revenue_minor, access.business.currency)}</td><td className="money text-right">{formatMoney(row.cost_minor, access.business.currency)}</td><td className={`money text-right font-medium ${profit < 0 ? "text-danger" : ""}`}>{formatMoney(profit, access.business.currency)}</td><td className="money text-right">{margin === null ? "—" : `${margin.toFixed(1)}%`}</td></tr>; })}</tbody><tfoot><tr className="border-t border-border-strong bg-surface font-semibold"><td className="h-11 px-3" colSpan={3}>Total</td><td className="money h-11 px-3 text-right">{formatMoney(totals.revenue, access.business.currency)}</td><td className="money h-11 px-3 text-right">{formatMoney(totals.cost, access.business.currency)}</td><td className="money h-11 px-3 text-right">{formatMoney(totals.revenue - totals.cost, access.business.currency)}</td><td className="money h-11 px-3 text-right">{totals.revenue ? `${(((totals.revenue - totals.cost) / totals.revenue) * 100).toFixed(1)}%` : "—"}</td></tr></tfoot></table></div> : <div className="rounded-lg border border-border bg-surface py-10 text-center"><p className="font-medium">No projects match these filters</p><p className="mt-1 text-sm text-muted-foreground">Adjust the date, status, or customer selection.</p></div>}
  </div>;
}
