import Link from "next/link";
import { ArrowLeft, CalendarDays, CircleUserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { NoticeToast } from "@/components/notice-toast";
import { requireModule } from "@/core/permissions/require-module";
import { formatDate, formatMoney } from "@/core/format";
import { ProjectFiles, ProjectNotes } from "@/modules/projects/project-collaboration";
import { getProject } from "@/modules/projects/project-service";
import { ProjectStatusBadge } from "@/modules/projects/project-status";
import { ProjectViewActions } from "@/modules/projects/project-view-actions";
import { getProjectOperationalView, type ProjectDocumentRow } from "@/modules/projects/project-view-service";

function Metric({ label, value, currency, emphasis = false }: { label: string; value: number | null; currency: string; emphasis?: boolean }) {
  return <div className="bg-surface-raised px-4 py-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className={`money mt-1 text-base ${emphasis ? "font-semibold" : "font-medium"}`}>{value === null ? "Not tracked" : formatMoney(value, currency)}</dd></div>;
}

function DocumentTable({ businessId, rows, kind, currency }: { businessId: string; rows: ProjectDocumentRow[]; kind: "sales/invoices" | "sales/credit-notes" | "purchases/orders" | "purchases/invoices"; currency: string }) {
  if (!rows.length) return <p className="py-6 text-center text-sm text-muted-foreground">No related documents.</p>;
  return <div className="overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Document</th><th>Date</th><th>Customer / Supplier</th><th>Status</th><th className="text-right!">Native project net</th><th className="text-right!">Base project net</th><th className="text-right!">Base document total</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/b/${businessId}/${kind}/${row.id}`} className="tabular font-medium text-primary hover:underline">{row.number}</Link></td><td>{formatDate(row.date)}</td><td>{row.party}</td><td className="capitalize">{row.status.replaceAll("_", " ")}</td><td className="money text-right">{formatMoney(row.foreignNetMinor, row.currencyCode)}</td><td className="money text-right">{formatMoney(row.netMinor, currency)}</td><td className="money text-right">{formatMoney(row.totalMinor, currency)}</td></tr>)}</tbody></table></div>;
}

export default async function ProjectViewPage({ params, searchParams }: { params: Promise<{ businessId: string; projectId: string }>; searchParams: Promise<{ notice?: string }> }) {
  const { businessId, projectId } = await params;
  const { notice } = await searchParams;
  const { user, access } = await requireModule(businessId, "projects");
  const project = getProject(businessId, user.id, projectId);
  if (!project) notFound();
  const operational = getProjectOperationalView(businessId, user.id, projectId);
  const currency = access.business.currency;
  return <div className="page-container">
    <NoticeToast message={notice} />
    <Link href={`/b/${businessId}/projects`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Projects</Link>
    <div className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="tabular text-sm font-semibold text-primary">{project.code}</span><ProjectStatusBadge status={project.status} /></div><h1 className="page-title mt-1">{project.name}</h1><p className="mt-2 text-sm text-muted-foreground">{project.customerId ? <Link href={`/b/${businessId}/customers/${project.customerId}`} className="font-medium text-foreground hover:text-primary hover:underline">{project.customerName}</Link> : "No customer assigned"}</p></div><ProjectViewActions businessId={businessId} projectId={projectId} customerId={project.customerId} /></div>
    <nav aria-label="Project sections" className="mb-5 overflow-x-auto border-b border-border"><div className="flex min-w-max gap-6">{[["overview", "Overview"], ["sales", "Sales"], ["purchases", "Purchases"], ["activity", "Activity"], ["files", "Files"]].map(([href, label]) => <a key={href} href={`#${href}`} className="border-b-2 border-transparent px-0.5 py-2.5 text-[13px] font-medium text-muted-foreground hover:border-primary hover:text-foreground">{label}</a>)}</div></nav>

    <section id="overview" aria-labelledby="overview-heading" className="scroll-mt-20"><h2 id="overview-heading" className="sr-only">Overview</h2><dl aria-label="Project financial actuals" className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><Metric label="Revenue" value={project.revenueMinor} currency={currency} /><Metric label="Costs" value={project.costMinor} currency={currency} /><Metric label="Gross Profit" value={project.profitMinor} currency={currency} emphasis /><div className="bg-surface-raised px-4 py-3"><dt className="text-xs text-muted-foreground">Margin</dt><dd className="money mt-1 text-base font-semibold">{project.marginPercent === null ? "—" : `${project.marginPercent.toFixed(1)}%`}</dd></div></dl>
      <dl aria-label="Project operational metrics" className="mt-3 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><Metric label="Quoted" value={operational.metrics.quotedMinor} currency={currency} /><Metric label="Invoiced (net)" value={operational.metrics.invoicedMinor} currency={currency} /><Metric label="Collected" value={operational.metrics.collectedMinor} currency={currency} /><Metric label="Outstanding" value={operational.metrics.outstandingMinor} currency={currency} /><Metric label="PO Committed (net)" value={operational.metrics.committedMinor} currency={currency} /><Metric label="Purchased (net)" value={operational.metrics.purchasedMinor} currency={currency} /><Metric label="Paid" value={operational.metrics.paidMinor} currency={currency} /><div className="bg-surface-raised px-4 py-3"><dt className="text-xs text-muted-foreground">Payment attribution</dt><dd className="mt-1 text-sm font-medium">Single-project documents</dd></div></dl>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.05fr_0.95fr]"><section className="rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Budget against actual</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div className="rounded-md bg-surface px-3 py-3"><dt className="text-xs text-muted-foreground">Revenue budget</dt><dd className="money mt-1 font-semibold">{project.budgetRevenueMinor === null ? "Not set" : formatMoney(project.budgetRevenueMinor, currency)}</dd><p className="money mt-1 text-xs text-muted-foreground">Variance {project.budgetRevenueMinor === null ? "—" : formatMoney(project.budgetRevenueMinor - project.revenueMinor, currency)}</p></div><div className="rounded-md bg-surface px-3 py-3"><dt className="text-xs text-muted-foreground">Cost budget</dt><dd className="money mt-1 font-semibold">{project.budgetCostMinor === null ? "Not set" : formatMoney(project.budgetCostMinor, currency)}</dd><p className="money mt-1 text-xs text-muted-foreground">Variance {project.budgetCostMinor === null ? "—" : formatMoney(project.budgetCostMinor - project.costMinor, currency)}</p></div></dl></section><section className="rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Project details</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Schedule</dt><dd className="mt-1 flex items-start gap-2"><CalendarDays className="mt-0.5 size-4 text-muted-foreground" /><span>{project.startDate ? formatDate(project.startDate) : "No start date"} → {project.targetEndDate ? formatDate(project.targetEndDate) : "No target end"}</span></dd></div><div><dt className="text-xs text-muted-foreground">Manager / contact</dt><dd className="mt-1 flex items-center gap-2"><CircleUserRound className="size-4 text-muted-foreground" />{project.managerName || "Not assigned"}</dd></div>{project.description && <div className="sm:col-span-2"><dt className="text-xs text-muted-foreground">Description</dt><dd className="mt-1 whitespace-pre-wrap leading-6">{project.description}</dd></div>}</dl></section></div>
    </section>

    <section id="sales" className="mt-8 scroll-mt-20"><div className="mb-3"><h2 className="text-base font-semibold">Sales</h2><p className="mt-1 text-sm text-muted-foreground">Posted line allocations drive revenue; attributable receipts are limited to single-project invoices.</p></div><div className="data-panel"><div className="border-b border-border px-4 py-3 text-sm font-semibold">Sales Invoices</div><DocumentTable businessId={businessId} rows={operational.salesInvoices} kind="sales/invoices" currency={currency} /></div><div className="data-panel mt-3"><div className="border-b border-border px-4 py-3 text-sm font-semibold">Sales Credit Notes</div><DocumentTable businessId={businessId} rows={operational.creditNotes} kind="sales/credit-notes" currency={currency} /></div>{operational.receipts.length > 0 && <div className="data-panel mt-3 overflow-x-auto"><div className="border-b border-border px-4 py-3 text-sm font-semibold">Attributable Receipts</div><table className="data-table min-w-[620px]"><thead><tr><th>Receipt</th><th>Date</th><th>Invoice</th><th className="text-right!">Allocated</th></tr></thead><tbody>{operational.receipts.map((row) => <tr key={row.id}><td><Link href={`/b/${businessId}/sales/receipts/${row.id}`} className="tabular font-medium text-primary hover:underline">{row.number}</Link></td><td>{formatDate(row.date)}</td><td><Link href={`/b/${businessId}/sales/invoices/${row.invoice_id}`} className="tabular text-primary hover:underline">{row.invoice_number}</Link></td><td className="money text-right">{formatMoney(row.allocated_minor, currency)}</td></tr>)}</tbody></table></div>}</section>

    <section id="purchases" className="mt-8 scroll-mt-20"><div className="mb-3"><h2 className="text-base font-semibold">Purchases</h2><p className="mt-1 text-sm text-muted-foreground">Purchase Orders show operational commitment; posted expense lines provide actual cost.</p></div><div className="data-panel"><div className="border-b border-border px-4 py-3 text-sm font-semibold">Purchase Orders</div><DocumentTable businessId={businessId} rows={operational.purchaseOrders} kind="purchases/orders" currency={currency} /></div><div className="data-panel mt-3"><div className="border-b border-border px-4 py-3 text-sm font-semibold">Purchase Invoices</div><DocumentTable businessId={businessId} rows={operational.purchaseInvoices} kind="purchases/invoices" currency={currency} /></div>{operational.payments.length > 0 && <div className="data-panel mt-3 overflow-x-auto"><div className="border-b border-border px-4 py-3 text-sm font-semibold">Attributable Supplier Payments</div><table className="data-table min-w-[620px]"><thead><tr><th>Payment</th><th>Date</th><th>Invoice</th><th className="text-right!">Allocated</th></tr></thead><tbody>{operational.payments.map((row) => <tr key={row.id}><td><Link href={`/b/${businessId}/purchases/payments/${row.id}`} className="tabular font-medium text-primary hover:underline">{row.number}</Link></td><td>{formatDate(row.date)}</td><td><Link href={`/b/${businessId}/purchases/invoices/${row.invoice_id}`} className="tabular text-primary hover:underline">{row.invoice_number}</Link></td><td className="money text-right">{formatMoney(row.allocated_minor, currency)}</td></tr>)}</tbody></table></div>}</section>

    <section id="activity" className="mt-8 scroll-mt-20"><h2 className="text-base font-semibold">Activity</h2><div className="mt-3 grid gap-5 lg:grid-cols-[1fr_0.9fr]"><div className="data-panel divide-y divide-border">{operational.activity.length ? operational.activity.map((event) => <div key={event.id} className="flex items-start justify-between gap-4 px-4 py-3"><div><p className="text-sm font-medium">{event.href ? <Link href={`/b/${businessId}${event.href}`} className="hover:text-primary hover:underline">{event.label}</Link> : event.label}</p><p className="mt-0.5 text-xs text-muted-foreground">{formatDate(event.at)}</p></div>{event.amountMinor !== null && <span className="money text-sm font-medium">{formatMoney(event.amountMinor, currency)}</span>}</div>) : <p className="px-4 py-6 text-sm text-muted-foreground">No activity yet.</p>}</div><section className="rounded-lg border border-border bg-surface-raised p-4"><h3 className="text-sm font-semibold">Notes</h3><div className="mt-3"><ProjectNotes businessId={businessId} projectId={projectId} notes={operational.notes} /></div></section></div></section>
    <section id="files" className="mt-8 scroll-mt-20"><h2 className="text-base font-semibold">Files</h2><p className="mt-1 text-sm text-muted-foreground">Business-local attachments are included in portable business backups.</p><div className="mt-3 rounded-lg border border-border bg-surface-raised p-4"><ProjectFiles businessId={businessId} projectId={projectId} attachments={operational.attachments} /></div></section>
  </div>;
}
