"use client";

import { useState } from "react";
import Link from "next/link";
import { Ban, BookOpenText, CircleDollarSign, Copy, Download, MoreHorizontal, PackagePlus, Pencil, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { DialogContent, DialogDescription, DialogRoot, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { deletePurchaseInvoiceAction, duplicatePurchaseInvoiceAction, voidPurchaseInvoiceAction } from "./actions";
import type { PurchaseInvoiceStatus } from "./purchase-invoice-service";
import { FormError } from "@/components/form-error";

type Confirm = "delete" | "void" | null;
export function PurchaseInvoiceViewActions({ businessId, invoiceId, internalNumber, documentStatus, balanceMinor, journalEntryId, inventoryEnabled, hasInventoryLines }: { businessId: string; invoiceId: string; internalNumber: string; documentStatus: PurchaseInvoiceStatus; balanceMinor: number; journalEntryId: string | null; inventoryEnabled: boolean; hasInventoryLines: boolean }) {
  const [confirm, setConfirm] = useState<Confirm>(null); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const router = useRouter();
  async function duplicate() { setPending(true); const result = await duplicatePurchaseInvoiceAction(businessId, invoiceId); if (result?.error) { setPending(false); toast.error(result.error); } }
  async function run() { setPending(true); setError(""); const result = confirm === "delete" ? await deletePurchaseInvoiceAction(businessId, invoiceId) : await voidPurchaseInvoiceAction(businessId, invoiceId); setPending(false); if (result.error) return setError(result.error); setConfirm(null); if (confirm === "delete") router.push(`/b/${businessId}/purchases/invoices`); else router.refresh(); toast.success(confirm === "delete" ? "Draft purchase invoice deleted." : "Purchase invoice voided with a reversing journal."); }
  return <><div className="flex flex-wrap gap-2">{documentStatus !== "void" && <Button asChild><Link href={`/b/${businessId}/purchases/invoices/${invoiceId}/edit`}><Pencil className="size-4" /> Edit</Link></Button>}{inventoryEnabled && hasInventoryLines && documentStatus !== "void" && <Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/goods-receipts/new?invoiceId=${invoiceId}`}><PackagePlus className="size-4" /> Receive Goods</Link></Button>}{documentStatus === "posted" && balanceMinor > 0 && <Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/payments/new?invoiceId=${invoiceId}`}><CircleDollarSign className="size-4" /> Record Payment</Link></Button>}<Button asChild variant="secondary" className="hidden md:inline-flex"><a href={`/api/businesses/${businessId}/documents/purchase-invoice/${invoiceId}/pdf`} target="_blank" rel="noreferrer"><Download className="size-4" /> Print / PDF</a></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="secondary" aria-label="More actions">More <MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild className="md:hidden"><a href={`/api/businesses/${businessId}/documents/purchase-invoice/${invoiceId}/pdf`} target="_blank"><Download className="size-4" /> Print / PDF</a></DropdownMenuItem><DropdownMenuItem disabled={pending} onSelect={() => void duplicate()}><Copy className="size-4" /> Duplicate</DropdownMenuItem>{journalEntryId && <DropdownMenuItem asChild><Link href={`/b/${businessId}/accounting/journal/${journalEntryId}`}><BookOpenText className="size-4" /> View Journal Entry</Link></DropdownMenuItem>}{documentStatus !== "void" && <DropdownMenuSeparator />}{documentStatus === "posted" && <DropdownMenuItem className="text-danger focus:text-danger" onSelect={() => setConfirm("void")}><Ban className="size-4" /> Void</DropdownMenuItem>}{documentStatus === "draft" && <DropdownMenuItem className="text-danger focus:text-danger" onSelect={() => setConfirm("delete")}><Trash2 className="size-4" /> Delete draft</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div>
    <DialogRoot open={!!confirm} onOpenChange={(open) => !open && setConfirm(null)}><DialogContent><DialogTitle>{confirm === "delete" ? `Delete ${internalNumber}?` : `Void ${internalNumber}?`}</DialogTitle><DialogDescription>{confirm === "delete" ? "This permanently removes the non-posting draft." : "This retains the bill and creates a balanced reversing journal. Bills with payment allocations cannot be voided."}</DialogDescription>{error && <FormError message={error} />}<div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => setConfirm(null)}>Cancel</Button><Button variant="danger" disabled={pending} onClick={run}>{confirm === "delete" ? "Delete draft" : "Void invoice"}</Button></div></DialogContent></DialogRoot></>;
}
