import Link from "next/link";
import { ArrowLeft, Download, ExternalLink } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireModule } from "@/core/permissions/require-module";
import { formatMoney } from "@/core/format";
import { emirateLabels, vatReportBuckets, type Emirate, type VatReportBucket } from "@/modules/tax/uae-vat-config";
import { getVatPeriod } from "@/modules/tax/vat-period-service";
import { getVatWorkingPaper } from "@/modules/tax/vat-report-service";
import { VatAdjustmentForm, VatWorkflowControls } from "@/modules/tax/vat-period-controls";

const statusLabel: Record<string, string> = { open: "Open", prepared: "Prepared", finalized: "Finalized", filed_externally: "Filed Externally", reopened: "Reopened" };

export default async function VatWorkingPaperPage({ params }: { params: Promise<{ businessId: string; periodId: string }> }) {
  const { businessId, periodId } = await params;
  const { user, access } = await requireModule(businessId, "reports");
  const record = getVatPeriod(businessId, user.id, periodId);
  if (!record) notFound();
  const report = getVatWorkingPaper(businessId, user.id, periodId);
  const period = record.period;
  const status = String(period.status);
  const isAdmin = access.membership.role === "administrator";
  return <div className="page-container max-w-[1180px] space-y-6">
    <div><Link href={`/b/${businessId}/tax/vat`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> VAT periods</Link><div className="page-header"><div><div className="flex flex-wrap items-center gap-2"><h1 className="page-title">VAT Return Working Paper</h1><Badge tone={status === "filed_externally" ? "success" : status === "finalized" ? "info" : "neutral"}>{statusLabel[status] ?? status}</Badge>{report.reviewCount > 0 && <Badge tone="warning">Needs Review</Badge>}</div><p className="page-description">{String(period.period_reference)} · {String(period.start_date)} – {String(period.end_date)} · Due {String(period.filing_due_date)}</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="secondary"><a href={`/api/businesses/${businessId}/tax/vat/export?periodId=${periodId}&type=summary`}><Download className="size-4" /> Export Working Paper</a></Button><Button asChild variant="secondary"><a href={`/api/businesses/${businessId}/tax/vat/export?periodId=${periodId}&type=detail`}><Download className="size-4" /> Export Transaction Detail</a></Button></div></div></div>
    {status === "filed_externally" && <div className="rounded-md border border-success/25 bg-success/10 px-3 py-2.5 text-sm"><strong>Filed Externally</strong> records a filing made outside this ERP. No FTA or EmaraTax submission was performed by this application.</div>}
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-border bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Total Output VAT</p><p className="money mt-1 text-lg font-semibold">{formatMoney(report.totalOutputVatMinor, access.business.currency)}</p></div><div className="rounded-lg border border-border bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Recoverable Input VAT</p><p className="money mt-1 text-lg font-semibold">{formatMoney(report.totalRecoverableVatMinor, access.business.currency)}</p></div><div className="rounded-lg border border-border bg-surface-raised p-4"><p className="text-xs text-muted-foreground">{report.netVatMinor >= 0 ? "Net VAT Due" : "Net VAT Recoverable"}</p><p className="money mt-1 text-lg font-semibold">{formatMoney(Math.abs(report.netVatMinor), access.business.currency)}</p></div></div>
    <section><h2 className="mb-2 text-base font-semibold">Calculated working-paper buckets</h2><div className="data-panel overflow-x-auto"><table className="data-table min-w-[720px]"><thead><tr><th>Bucket</th><th className="text-right!">Transactions</th><th className="text-right!">Net</th><th className="text-right!">VAT</th><th /></tr></thead><tbody>{vatReportBuckets.map((bucket) => { const values = report.buckets[bucket.id as VatReportBucket]; return <tr key={bucket.id}><td>{bucket.label}</td><td className="text-right tabular-nums">{values.count}</td><td className="money text-right">{formatMoney(values.netMinor, access.business.currency)}</td><td className="money text-right">{formatMoney(bucket.id.includes("purchase") ? values.recoverableVatMinor : values.outputVatMinor, access.business.currency)}</td><td className="text-right"><Link className="text-sm font-medium text-primary" href={`/b/${businessId}/reports/vat-transactions?periodId=${periodId}&bucket=${bucket.id}`}>Drill down</Link></td></tr>; })}</tbody></table></div></section>
    <section><h2 className="mb-2 text-base font-semibold">Standard-rated Sales by Emirate</h2><div className="data-panel overflow-x-auto"><table className="data-table min-w-[620px]"><thead><tr><th>Emirate</th><th className="text-right!">Transactions</th><th className="text-right!">Net</th><th className="text-right!">Output VAT</th></tr></thead><tbody>{report.emirateBreakdown.map((row) => <tr key={row.emirate}><td>{emirateLabels[row.emirate as Emirate]}</td><td className="text-right tabular-nums">{row.count}</td><td className="money text-right">{formatMoney(row.netMinor, access.business.currency)}</td><td className="money text-right">{formatMoney(row.vatMinor, access.business.currency)}</td></tr>)}</tbody></table></div></section>
    <section><h2 className="mb-2 text-base font-semibold">Calculated, adjustments, and Return Total</h2><div className="data-panel p-4"><dl className="ml-auto max-w-md space-y-2 text-sm"><div className="flex justify-between"><dt>Calculated Output VAT</dt><dd className="money">{formatMoney(report.calculatedOutputVatMinor, access.business.currency)}</dd></div><div className="flex justify-between"><dt>Output VAT adjustments</dt><dd className="money">{formatMoney(report.outputAdjustmentMinor, access.business.currency)}</dd></div><div className="flex justify-between font-medium"><dt>Return Total Output VAT</dt><dd className="money">{formatMoney(report.totalOutputVatMinor, access.business.currency)}</dd></div><div className="mt-3 flex justify-between border-t border-border pt-3"><dt>Calculated Recoverable Input VAT</dt><dd className="money">{formatMoney(report.calculatedRecoverableVatMinor, access.business.currency)}</dd></div><div className="flex justify-between"><dt>Input VAT adjustments</dt><dd className="money">{formatMoney(report.inputAdjustmentMinor, access.business.currency)}</dd></div><div className="flex justify-between font-medium"><dt>Return Total Recoverable Input VAT</dt><dd className="money">{formatMoney(report.totalRecoverableVatMinor, access.business.currency)}</dd></div></dl></div></section>
    {report.adjustments.length > 0 && <section><h2 className="mb-2 text-base font-semibold">Manual adjustments</h2><div className="data-panel overflow-x-auto"><table className="data-table min-w-[760px]"><thead><tr><th>Type</th><th>Reason / reference</th><th className="text-right!">Amount</th><th className="text-right!">VAT</th><th>Audit</th></tr></thead><tbody>{report.adjustments.map((adjustment) => <tr key={adjustment.id}><td>{adjustment.report_bucket === "output_vat_adjustment" ? "Output VAT adjustment" : "Input VAT adjustment"}</td><td><span className="font-medium">{adjustment.reason}</span>{adjustment.reference && <span className="ml-1 text-muted-foreground">· {adjustment.reference}</span>}</td><td className="money text-right">{formatMoney(adjustment.amount_minor, access.business.currency)}</td><td className="money text-right">{formatMoney(adjustment.vat_amount_minor, access.business.currency)}</td><td className="text-xs text-muted-foreground">{adjustment.created_at} · {adjustment.created_by}</td></tr>)}</tbody></table></div></section>}
    <section><h2 className="mb-2 text-base font-semibold">VAT reconciliation</h2><div className="data-panel overflow-x-auto"><table className="data-table min-w-[640px]"><thead><tr><th>Control</th><th className="text-right!">Tax entries</th><th className="text-right!">GL movement</th><th className="text-right!">Difference</th></tr></thead><tbody><tr><td>Output VAT</td><td className="money text-right">{formatMoney(report.calculatedOutputVatMinor, access.business.currency)}</td><td className="money text-right">{formatMoney(report.reconciliation.outputGlMinor, access.business.currency)}</td><td className="money text-right">{formatMoney(report.reconciliation.outputDifferenceMinor, access.business.currency)}</td></tr><tr><td>Recoverable Input VAT</td><td className="money text-right">{formatMoney(report.calculatedRecoverableVatMinor, access.business.currency)}</td><td className="money text-right">{formatMoney(report.reconciliation.inputGlMinor, access.business.currency)}</td><td className="money text-right">{formatMoney(report.reconciliation.inputDifferenceMinor, access.business.currency)}</td></tr></tbody></table></div></section>
    {report.reviewCount > 0 && <div className="rounded-md border border-warning/30 bg-warning/10 px-3 py-2.5 text-sm">This period has {report.reviewCount} unresolved historical VAT review item(s). <Link className="font-medium underline" href={`/b/${businessId}/tax/vat/review`}>Open VAT Data Review</Link>.</div>}
    <VatAdjustmentForm businessId={businessId} periodId={periodId} disabled={!isAdmin || ["finalized", "filed_externally"].includes(status)} />
    <VatWorkflowControls businessId={businessId} periodId={periodId} status={status} isAdmin={isAdmin} />
    <section><h2 className="mb-2 text-base font-semibold">Audit and snapshots</h2><div className="data-panel divide-y divide-border">{record.audit.map((row) => <div key={String(row.id)} className="flex flex-wrap items-center justify-between gap-2 px-4 py-3 text-sm"><span><strong>{String(row.action).replaceAll("_", " ")}</strong>{row.reason_or_reference ? ` · ${String(row.reason_or_reference)}` : ""}</span><span className="text-muted-foreground">{String(row.created_at)} · {String(row.created_by)}</span></div>)}{record.snapshots.length > 0 && <div className="px-4 py-3 text-sm text-muted-foreground">{record.snapshots.length} immutable snapshot(s) retained, including finalized/filed figures.</div>}</div></section>
    <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><ExternalLink className="size-3.5" /> Working papers support preparation only and are not professional tax advice.</p>
  </div>;
}
