import Link from "next/link";
import { ArrowLeft, Braces } from "lucide-react";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { formatDateTime } from "@/core/format";
import { requireModule } from "@/core/permissions/require-module";
import { EInvoiceDocumentControls } from "@/modules/einvoicing/document-controls";
import { getEInvoiceDocument } from "@/modules/einvoicing/einvoice-service";
import type { EInvoiceValidationReport } from "@/modules/einvoicing/einvoice-types";
import { EInvoiceStatusBadge } from "@/modules/einvoicing/status-badge";

export default async function EInvoiceDetailPage({ params }: { params: Promise<{ businessId: string; documentId: string }> }) {
  const { businessId, documentId } = await params;
  const { user } = await requireModule(businessId, "sales");
  const document = getEInvoiceDocument(businessId, user.id, documentId);
  if (!document) notFound();
  const source = document.source as { number: string; date: string; customer_name: string };
  const validation = document.validation as EInvoiceValidationReport | null;
  const sourceHref = document.sourceType === "sales_invoice" ? `/b/${businessId}/sales/invoices/${document.sourceId}` : `/b/${businessId}/sales/credit-notes/${document.sourceId}`;
  return <div className="page-container">
    <Link href={`/b/${businessId}/einvoicing`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Electronic Invoices</Link>
    <div className="page-header flex-col items-stretch sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h1 className="page-title">{source.number}</h1><EInvoiceStatusBadge status={document.status} /></div><p className="page-description">{source.customer_name} · {document.documentType === "invoice" ? "Sales Invoice" : "Sales Credit Note"}</p></div><div className="flex flex-wrap gap-2 sm:flex-nowrap"><Button asChild variant="ghost"><Link href={sourceHref}>Open source</Link></Button>{document.xmlPayload && <Button asChild variant="secondary"><a href={`/api/businesses/${businessId}/einvoicing/${document.id}/xml`}><Braces className="size-4" /> Download XML</a></Button>}</div></div>
    <section className="mb-5 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">UUID</p><p className="mt-1 break-all font-mono text-xs">{document.uuid}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Specification</p><p className="mt-1">PINT-AE {document.specificationVersion}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Exchange</p><p className="mt-1 capitalize">{document.exchangeStatus ?? "Not submitted"}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Reporting</p><p className="mt-1 capitalize">{document.reportingStatus ?? "Not submitted"}</p></div></section>
    <section className="mb-5 rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Validation</h2>{validation ? <><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(validation.layers).map(([name, layer]) => <div key={name} className="rounded-md border border-border p-3"><p className="text-xs capitalize text-muted-foreground">{name.replace(/([A-Z])/g, " $1")}</p><p className="mt-1 text-sm font-medium">{layer.valid ? "Passed" : `${layer.issueCount} issue${layer.issueCount === 1 ? "" : "s"}`}</p></div>)}</div>{validation.issues.length ? <ul className="mt-4 divide-y divide-border rounded-md border border-border">{validation.issues.map((entry, index) => <li key={`${entry.ruleId}-${index}`} className="p-3"><p className="font-mono text-xs text-foreground">{entry.layer} · {entry.ruleId}</p><p className="mt-1 text-sm text-muted-foreground">{entry.message}</p>{entry.path && <p className="mt-1 break-all font-mono text-[11px] text-muted-foreground">{entry.path}</p>}</li>)}</ul> : <p className="mt-4 text-sm text-success">Readiness, canonical mapping, PINT UBL, and PINT-AE validation passed.</p>}</> : <p className="mt-3 text-sm text-muted-foreground">Prepare the source document to create a validation report.</p>}<div className="mt-5"><EInvoiceDocumentControls businessId={businessId} sourceType={document.sourceType} sourceId={document.sourceId} documentId={document.id} status={document.status} /></div></section>
    <section className="rounded-lg border border-border bg-surface-raised"><div className="border-b border-border px-5 py-4"><h2 className="text-base font-semibold">Submission history</h2><p className="mt-1 text-sm text-muted-foreground">Every Mock ASP attempt is append-only and explicitly labelled.</p></div>{document.submissions.length ? <div className="overflow-x-auto"><table className="data-table min-w-[820px]"><thead><tr><th>Attempt</th><th>Status</th><th>Provider</th><th>Exchange</th><th>Reporting</th><th>Response</th><th>Submitted</th></tr></thead><tbody>{document.submissions.map((attempt) => <tr key={String(attempt.id)}><td className="tabular">#{attempt.attempt_number}</td><td>{attempt.status}</td><td>{attempt.provider_key} ({attempt.provider_environment})</td><td>{attempt.exchange_status ?? "—"}</td><td>{attempt.reporting_status ?? "—"}</td><td className="font-mono text-xs">{attempt.response_code ?? attempt.error_message ?? "—"}</td><td>{formatDateTime(String(attempt.submitted_at))}</td></tr>)}</tbody></table></div> : <div className="p-7 text-center text-sm text-muted-foreground">No submission attempts yet.</div>}</section>
  </div>;
}
