import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { formatDate, formatMoney } from "@/core/format";
import { requireModule } from "@/core/permissions/require-module";
import { getReconciliationSummary } from "@/modules/banking/banking-report-service";

export default async function ReconciliationSummaryPage({ params }: { params: Promise<{ businessId: string }> }) {
  const { businessId } = await params; const { user, access } = await requireModule(businessId, "reports"); await requireModule(businessId, "banking"); const rows = getReconciliationSummary(businessId, user.id);
  return <div className="page-container"><Link href={`/b/${businessId}/reports`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Reports</Link><div className="page-header"><div><h1 className="page-title">Reconciliation Summary</h1><p className="page-description">Latest completed statement evidence compared with the mapped GL Book Balance.</p></div></div>{rows.length ? <div className="data-panel"><table className="data-table min-w-[900px]"><thead><tr><th>Bank Account</th><th>Last Reconciled</th><th className="text-right!">Statement Balance</th><th className="text-right!">Book Balance at Date</th><th className="text-right!">Difference</th><th className="text-right!">Unmatched</th><th>Status</th></tr></thead><tbody>{rows.map((row) => { const difference = row.statement_balance_minor === null ? null : row.statement_balance_minor - row.book_balance_minor; return <tr key={row.id}><td><Link href={`/b/${businessId}/banking/accounts/${row.id}?section=reconciliation`} className="font-medium text-primary hover:underline">{row.name}</Link></td><td>{row.last_reconciled_date ? formatDate(row.last_reconciled_date) : "Never"}</td><td className="money text-right">{row.statement_balance_minor === null ? "—" : formatMoney(row.statement_balance_minor, access.business.currency)}</td><td className="money text-right">{formatMoney(row.book_balance_minor, access.business.currency)}</td><td className="money text-right">{difference === null ? "—" : formatMoney(difference, access.business.currency)}</td><td className="tabular text-right">{row.outstanding_count}</td><td><Badge tone={row.last_reconciled_date ? "success" : "neutral"}>{row.last_reconciled_date ? "Reconciled" : "Not reconciled"}</Badge></td></tr>; })}</tbody></table></div> : <div className="rounded-lg border border-border bg-surface py-10 text-center"><p className="font-medium">No Bank Accounts</p><p className="mt-1 text-sm text-muted-foreground">Create a Bank Account before reconciling.</p></div>}</div>;
}
