import Link from "next/link";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate, formatMoney } from "@/core/format";
import { requireModule } from "@/core/permissions/require-module";
import { journalSourceHref, journalSourceLabel } from "@/modules/accounting/journal-source";
import { minorToInput } from "@/modules/accounting/calculations/money";
import { getBankAccount } from "@/modules/banking/bank-account-service";
import { CompleteReconciliationButton, ReconciliationStartForm } from "@/modules/banking/reconciliation-controls";
import { getReconciliationSnapshot } from "@/modules/banking/reconciliation-service";

export default async function ReconcilePage({ params, searchParams }: { params: Promise<{ businessId: string; accountId: string }>; searchParams: Promise<{ reconciliationId?: string }> }) {
  const { businessId, accountId } = await params; const query = await searchParams; const { user, access } = await requireModule(businessId, "banking"); const account = getBankAccount(businessId, user.id, accountId); if (!account) notFound();
  const snapshot = query.reconciliationId ? getReconciliationSnapshot(businessId, user.id, query.reconciliationId, accountId) : null; if (query.reconciliationId && !snapshot) notFound();
  return <div className="page-container max-w-[1200px]"><Link href={`/b/${businessId}/banking/accounts/${accountId}?section=reconciliation`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> {account.name}</Link><div className="page-header"><div><div className="flex items-center gap-2"><h1 className="page-title">Reconciliation</h1>{snapshot && <Badge tone={snapshot.reconciliation.status === "completed" ? "success" : "warning"}>{snapshot.reconciliation.status === "completed" ? "Completed" : "Draft"}</Badge>}</div><p className="page-description">Compare statement evidence with the mapped GL account. Reconciliation never changes the ledger.</p></div></div>
    {!snapshot ? <ReconciliationStartForm businessId={businessId} accountId={accountId} initial={{ statementDate: new Date().toISOString().slice(0, 10), statementEndingBalance: minorToInput(account.statement_balance_minor ?? account.book_balance_minor) }} /> : <div className="space-y-6">
      <div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><div className="bg-surface-raised px-4 py-3"><p className="text-xs text-muted-foreground">Statement Ending Balance</p><p className="money mt-1 text-lg font-semibold">{formatMoney(snapshot.reconciliation.statement_ending_balance_minor, access.business.currency)}</p><p className="mt-1 text-xs text-muted-foreground">At {formatDate(snapshot.reconciliation.statement_date)}</p></div><div className="bg-surface-raised px-4 py-3"><p className="text-xs text-muted-foreground">Book Balance at Date</p><p className="money mt-1 text-lg font-semibold">{formatMoney(snapshot.bookBalanceMinor, access.business.currency)}</p><p className="mt-1 text-xs text-muted-foreground">Mapped GL {account.ledger_code}</p></div><div className="bg-surface-raised px-4 py-3"><p className="text-xs text-muted-foreground">Outstanding Net</p><p className="money mt-1 text-lg font-semibold">{formatMoney(snapshot.outstandingNetMinor, access.business.currency)}</p><p className="mt-1 text-xs text-muted-foreground">Book activity without statement match</p></div><div className={`px-4 py-3 ${snapshot.differenceMinor === 0 ? "bg-success/10" : "bg-warning/10"}`}><p className="text-xs text-muted-foreground">Difference</p><p className="money mt-1 text-lg font-semibold">{formatMoney(snapshot.differenceMinor, access.business.currency)}</p><p className="mt-1 text-xs text-muted-foreground">Statement − cleared Book Balance</p></div></div>
      <div className="flex flex-wrap items-start justify-between gap-4 rounded-lg border border-border bg-surface px-4 py-3"><div><p className="font-medium">Cleared Book Balance: <span className="money">{formatMoney(snapshot.clearedBookBalanceMinor, access.business.currency)}</span></p><p className="mt-1 text-xs text-muted-foreground">Book Balance less net outstanding GL activity. Imported lines and reconciliation do not post journals.</p></div>{snapshot.reconciliation.status === "draft" ? <CompleteReconciliationButton businessId={businessId} accountId={accountId} reconciliationId={snapshot.reconciliation.id} disabled={snapshot.differenceMinor !== 0} /> : <div className="flex items-center gap-2 text-sm font-medium text-success"><CheckCircle2 className="size-4" /> Completed {snapshot.reconciliation.completed_at ? formatDate(snapshot.reconciliation.completed_at) : ""}</div>}</div>
      <section><div className="mb-2 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Matched / Cleared</h2><span className="text-xs text-muted-foreground">{snapshot.cleared.length} statement lines</span></div>{snapshot.cleared.length ? <div className="data-panel"><table className="data-table min-w-[860px]"><thead><tr><th>Date</th><th>Description</th><th>Source</th><th>Journal</th><th className="text-right!">Amount</th></tr></thead><tbody>{snapshot.cleared.map((row) => <tr key={row.statement_line_id}><td>{formatDate(row.transaction_date)}</td><td>{row.description}</td><td>{journalSourceHref(businessId, row.matched_source_type, row.matched_source_id) ? <Link href={journalSourceHref(businessId, row.matched_source_type, row.matched_source_id)!} className="font-medium text-primary hover:underline">{journalSourceLabel(row.matched_source_type)}</Link> : journalSourceLabel(row.matched_source_type)}</td><td><Link href={`/b/${businessId}/accounting/journal/${row.journal_entry_id}`} className="tabular text-primary hover:underline">{row.entry_number}</Link></td><td className="money text-right">{formatMoney(row.amount_minor, access.business.currency)}</td></tr>)}</tbody></table></div> : <div className="rounded-md border border-border bg-surface px-4 py-5 text-sm text-muted-foreground">No matched statement lines through this date.</div>}</section>
      <section><div className="mb-2 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Outstanding GL Activity</h2><span className="text-xs text-muted-foreground">{snapshot.outstanding.length} entries</span></div>{snapshot.outstanding.length ? <div className="data-panel"><table className="data-table min-w-[820px]"><thead><tr><th>Date</th><th>Entry</th><th>Source</th><th>Description</th><th className="text-right!">Movement</th></tr></thead><tbody>{snapshot.outstanding.map((row) => <tr key={row.journal_entry_id}><td>{formatDate(row.date)}</td><td><Link href={`/b/${businessId}/accounting/journal/${row.journal_entry_id}`} className="tabular text-primary hover:underline">{row.entry_number}</Link></td><td>{journalSourceLabel(row.source_type)}</td><td>{row.description}</td><td className="money text-right">{formatMoney(row.amount_minor, access.business.currency)}</td></tr>)}</tbody></table></div> : <div className="rounded-md border border-border bg-surface px-4 py-5 text-sm text-muted-foreground">No outstanding GL activity through this date.</div>}</section>
      <section><div className="mb-2 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Unmatched Statement Lines</h2>{snapshot.unmatched.length > 0 && <Button asChild size="sm" variant="secondary"><Link href={`/b/${businessId}/banking/accounts/${accountId}?section=imported`}>Review matching</Link></Button>}</div>{snapshot.unmatched.length ? <div className="data-panel"><table className="data-table min-w-[760px]"><thead><tr><th>Date</th><th>Description</th><th>Reference</th><th className="text-right!">Amount</th></tr></thead><tbody>{snapshot.unmatched.map((row) => <tr key={row.id}><td>{formatDate(row.transaction_date)}</td><td>{row.description}</td><td>{row.reference || "—"}</td><td className="money text-right">{formatMoney(row.amount_minor, access.business.currency)}</td></tr>)}</tbody></table></div> : <div className="rounded-md border border-border bg-surface px-4 py-5 text-sm text-muted-foreground">No unmatched statement lines through this date.</div>}</section>
    </div>}
  </div>;
}
