import Link from "next/link";
import { ArrowLeft, ArrowDownToLine, ArrowUpFromLine, MoreHorizontal, Pencil, SlidersHorizontal } from "lucide-react";
import { notFound } from "next/navigation";
import { NoticeToast } from "@/components/notice-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { requireModule } from "@/core/permissions/require-module";
import { formatDate, formatMoney } from "@/core/format";
import { getInventoryItem } from "@/modules/inventory/inventory-item-service";
import { formatQuantityMicros, formatUnitCostMicros } from "@/modules/inventory/inventory-valuation";

const movementLabels: Record<string, string> = { goods_receipt: "Goods Receipt", delivery: "Delivery", adjustment_in: "Adjustment In", adjustment_out: "Adjustment Out", opening_balance: "Opening Balance" };
export default async function InventoryItemViewPage({ params, searchParams }: { params: Promise<{ businessId: string; itemId: string }>; searchParams: Promise<{ notice?: string }> }) { const { businessId, itemId } = await params; const { notice } = await searchParams; const { user, access } = await requireModule(businessId, "inventory"); const record = getInventoryItem(businessId, user.id, itemId); if (!record) notFound(); const item = record.item; const unit = String(item.unit_name); return <div className="page-container page-wide"><NoticeToast message={notice} /><Link href={`/b/${businessId}/inventory/items`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Inventory Items</Link><div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><h1 className="page-title">{String(item.name)}</h1><Badge tone={item.is_active ? "success" : "neutral"}>{item.is_active ? "Active" : "Inactive"}</Badge></div><p className="mt-1 tabular text-sm text-muted-foreground">{String(item.sku ?? "No SKU")} · Unit {unit}</p></div><div className="flex flex-wrap gap-2"><Button asChild><Link href={`/b/${businessId}/inventory/items/${itemId}/edit`}><Pencil className="size-4" /> Edit</Link></Button><Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/goods-receipts/new?itemId=${itemId}`}><ArrowDownToLine className="size-4" /> Receive Stock</Link></Button><Button asChild variant="secondary"><Link href={`/b/${businessId}/sales/delivery-notes/new?itemId=${itemId}`}><ArrowUpFromLine className="size-4" /> Deliver Stock</Link></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="secondary">More <MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link href={`/b/${businessId}/inventory/adjustments/new?itemId=${itemId}`}><SlidersHorizontal className="size-4" /> Adjust stock</Link></DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>
    <div className="mb-6 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-5"><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">On Hand</p><p className="money mt-1 text-lg font-semibold">{formatQuantityMicros(record.quantityMicros)} {unit}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">To Receive</p><p className="money mt-1 text-lg font-semibold">{formatQuantityMicros(record.toReceiveMicros)} {unit}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">To Deliver</p><p className="money mt-1 text-lg font-semibold">{formatQuantityMicros(record.toDeliverMicros)} {unit}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Average Cost</p><p className="money mt-1 text-lg font-semibold">{formatUnitCostMicros(record.averageUnitCostMicros, access.business.currency)}</p></div><div className="bg-surface-raised p-4"><p className="text-xs text-muted-foreground">Inventory Value</p><p className="money mt-1 text-lg font-semibold">{formatMoney(record.valueMinor, access.business.currency)}</p></div></div>
    <article className="rounded-lg border border-border bg-surface-raised p-5 sm:p-6"><section><h2 className="text-sm font-semibold">Overview</h2><div className="mt-3 grid gap-4 text-sm sm:grid-cols-2"><p className="text-muted-foreground">{String(item.description ?? "No description")}</p><dl className="grid grid-cols-2 gap-2"><dt className="text-muted-foreground">Sales account</dt><dd className="text-right">{String(item.sales_account_code)} {String(item.sales_account_name)}</dd><dt className="text-muted-foreground">Inventory Asset</dt><dd className="text-right">{String(item.asset_account_code)} {String(item.asset_account_name)}</dd><dt className="text-muted-foreground">Cost of Sales</dt><dd className="text-right">{String(item.cogs_account_code)} {String(item.cogs_account_name)}</dd></dl></div></section>
      <section className="mt-7 border-t border-border pt-5"><h2 className="text-sm font-semibold">Stock by location</h2><div className="mt-3 overflow-x-auto rounded-md border border-border"><table className="data-table min-w-[620px]"><thead><tr><th>Location</th><th className="text-right!">Quantity</th><th className="text-right!">Average Cost</th><th className="text-right!">Value</th></tr></thead><tbody>{record.locations.map((row) => <tr key={row.id}><td><Link href={`/b/${businessId}/inventory/locations/${row.id}`} className="font-medium text-primary hover:underline">{row.code} · {row.name}</Link></td><td className="money text-right">{formatQuantityMicros(row.quantity_micros)} {unit}</td><td className="money text-right">{formatUnitCostMicros(row.average_unit_cost_micros, access.business.currency)}</td><td className="money text-right">{formatMoney(row.value_minor, access.business.currency)}</td></tr>)}</tbody></table></div></section>
      <section className="mt-7 border-t border-border pt-5"><h2 className="text-sm font-semibold">Recent movements</h2>{record.movements.length ? <div className="mt-3 overflow-x-auto rounded-md border border-border"><table className="data-table min-w-[760px]"><thead><tr><th>Date</th><th>Type</th><th>Location</th><th>Reference</th><th className="text-right!">Quantity</th><th className="text-right!">Value</th></tr></thead><tbody>{record.movements.map((movement) => <tr key={String(movement.id)}><td>{formatDate(String(movement.date))}</td><td>{movementLabels[String(movement.movement_type)] ?? String(movement.movement_type)}</td><td>{String(movement.location_code)}</td><td className="text-muted-foreground">{String(movement.description ?? "—")}</td><td className={`money text-right ${Number(movement.quantity_delta_micros) < 0 ? "text-danger" : ""}`}>{formatQuantityMicros(Number(movement.quantity_delta_micros))} {unit}</td><td className="money text-right">{formatMoney(Number(movement.value_delta_minor), access.business.currency)}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-muted-foreground">No stock movements yet.</p>}</section>
      <section className="mt-7 border-t border-border pt-5"><h2 className="text-sm font-semibold">Purchases</h2>{record.purchases.length ? <div className="mt-3 overflow-x-auto rounded-md border border-border"><table className="data-table min-w-[720px]"><thead><tr><th>Purchase Order</th><th>Supplier</th><th>Status</th><th className="text-right!">Ordered</th><th className="text-right!">Received</th><th className="text-right!">Remaining</th></tr></thead><tbody>{record.purchases.map((row) => <tr key={row.id}><td><Link href={`/b/${businessId}/purchases/orders/${row.id}`} className="tabular font-medium text-primary hover:underline">{row.order_number}</Link></td><td>{row.supplier_name}</td><td className="capitalize">{row.status}</td><td className="money text-right">{formatQuantityMicros(row.ordered_micros)}</td><td className="money text-right">{formatQuantityMicros(row.received_micros)}</td><td className="money text-right">{formatQuantityMicros(Math.max(0, row.ordered_micros - row.received_micros))}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-muted-foreground">No Purchase Orders reference this item.</p>}</section>
      <section className="mt-7 border-t border-border pt-5"><h2 className="text-sm font-semibold">Sales</h2>{record.sales.length ? <div className="mt-3 overflow-x-auto rounded-md border border-border"><table className="data-table min-w-[720px]"><thead><tr><th>Sales Invoice</th><th>Customer</th><th>Status</th><th className="text-right!">Required</th><th className="text-right!">Delivered</th><th className="text-right!">Remaining</th></tr></thead><tbody>{record.sales.map((row) => <tr key={row.id}><td><Link href={`/b/${businessId}/sales/invoices/${row.id}`} className="tabular font-medium text-primary hover:underline">{row.invoice_number}</Link></td><td>{row.customer_name}</td><td className="capitalize">{row.document_status}</td><td className="money text-right">{formatQuantityMicros(row.required_micros)}</td><td className="money text-right">{formatQuantityMicros(row.delivered_micros)}</td><td className="money text-right">{formatQuantityMicros(Math.max(0, row.required_micros - row.delivered_micros))}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-muted-foreground">No Sales Invoices reference this item.</p>}</section>
    </article></div>; }
