"use client";
import { FormError } from "@/components/form-error";

import Link from "next/link";
import { useMemo, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle } from "lucide-react";
import { useForm, useWatch } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatMoney } from "@/core/format";
import { DocumentCurrencyFields, type DocumentCurrencyOption, type DocumentRateOption } from "@/modules/currency/document-currency-fields";
import { createSupplierPaymentAction } from "./actions";
import { supplierPaymentInputSchema, type SupplierPaymentInput } from "./supplier-payment-input";
import { SelectNative } from "@/components/ui/select-native";

type Option = { id: string; name: string }; type InvoiceOption = { id: string; internalNumber: string; supplierId: string; balanceMinor: number; currencyCode: string; minorUnit: number };
export function SupplierPaymentForm({ businessId, currency, suppliers, invoices, bankAccounts, currencies, rates, initial }: { businessId: string; currency: string; suppliers: Option[]; invoices: InvoiceOption[]; bankAccounts: Option[]; currencies: DocumentCurrencyOption[]; rates: DocumentRateOption[]; initial: SupplierPaymentInput }) {
  const [serverError, setServerError] = useState(""); const form = useForm<SupplierPaymentInput>({ resolver: zodResolver(supplierPaymentInputSchema), defaultValues: initial }); const { register, control, handleSubmit, setError, setValue, formState: { errors, isSubmitting } } = form;
  const supplierId = useWatch({ control, name: "supplierId" }); const invoiceId = useWatch({ control, name: "purchaseInvoiceId" }); const supplierInvoices = useMemo(() => invoices.filter((invoice) => invoice.supplierId === supplierId), [invoices, supplierId]); const selected = invoices.find((invoice) => invoice.id === invoiceId);
  const currencyCode = useWatch({ control, name: "currencyCode" }) || currency; const exchangeRateToBase = useWatch({ control, name: "exchangeRateToBase" }) || ""; const exchangeRateDate = useWatch({ control, name: "exchangeRateDate" }) || ""; const exchangeRateSource = useWatch({ control, name: "exchangeRateSource" }) || ""; const paymentDate = useWatch({ control, name: "date" }) || "";
  async function submit(values: SupplierPaymentInput) { setServerError(""); const result = await createSupplierPaymentAction(businessId, values); if (result.fieldErrors) for (const [field, messages] of Object.entries(result.fieldErrors)) setError(field as keyof SupplierPaymentInput, { message: messages[0] }); if (result.error) setServerError(result.error); }
  return <form onSubmit={handleSubmit(submit)} className="space-y-7" noValidate>{serverError && <FormError message={serverError} />}<section className="border-b border-border pb-7"><h2 className="text-base font-semibold">Payment details</h2><p className="mt-1 text-sm text-muted-foreground">Posting debits Accounts Payable and credits the selected Bank or Cash account.</p><div className="mt-5 grid gap-5 md:grid-cols-2">
    <div className="space-y-1.5"><Label htmlFor="supplierId">Supplier</Label><SelectNative id="supplierId"  {...register("supplierId", { onChange: () => setValue("purchaseInvoiceId", "") })} aria-invalid={!!errors.supplierId}><option value="">Choose a supplier…</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</SelectNative>{errors.supplierId && <p className="field-error">{errors.supplierId.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="purchaseInvoiceId">Purchase invoice</Label><SelectNative id="purchaseInvoiceId"  {...register("purchaseInvoiceId", { onChange: (event) => { const invoice = invoices.find((entry) => entry.id === event.target.value); const code = invoice?.currencyCode ?? currency; setValue("currencyCode", code); setValue("exchangeRateToBase", code === currency ? "1" : ""); setValue("exchangeRateDate", code === currency ? paymentDate : ""); setValue("exchangeRateSource", code === currency ? "Base" : ""); } })} aria-invalid={!!errors.purchaseInvoiceId}><option value="">Choose an outstanding invoice…</option>{supplierInvoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.internalNumber} · {formatMoney(invoice.balanceMinor, invoice.currencyCode, invoice.minorUnit)} outstanding</option>)}</SelectNative>{errors.purchaseInvoiceId && <p className="field-error">{errors.purchaseInvoiceId.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="date">Payment date</Label><Input id="date" type="date" {...register("date")} aria-invalid={!!errors.date} />{errors.date && <p className="field-error">{errors.date.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="bankAccountId">Pay from</Label><SelectNative id="bankAccountId"  {...register("bankAccountId")} aria-invalid={!!errors.bankAccountId}><option value="">Choose Bank or Cash…</option>{bankAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</SelectNative>{errors.bankAccountId && <p className="field-error">{errors.bankAccountId.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="amount">Amount</Label><Input id="amount" type="number" min="0.000001" step="0.000001" className="money text-right" {...register("amount")} aria-invalid={!!errors.amount} />{selected && <p className="text-xs text-muted-foreground">Maximum {formatMoney(selected.balanceMinor, selected.currencyCode, selected.minorUnit)}</p>}{errors.amount && <p className="field-error">{errors.amount.message}</p>}</div>
    <div className="space-y-1.5"><Label htmlFor="reference">Reference <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="reference" {...register("reference")} /></div>
    <div className="space-y-1.5 md:col-span-2"><Label htmlFor="description">Description <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="description" {...register("description")} /></div>
  </div></section><section className="border-b border-border pb-7"><h2 className="mb-4 text-base font-semibold">Settlement currency</h2><DocumentCurrencyFields baseCurrencyCode={currency} currencies={currencies} rates={rates} currencyCode={currencyCode} exchangeRateToBase={exchangeRateToBase} exchangeRateDate={exchangeRateDate} exchangeRateSource={exchangeRateSource} relevantDate={paymentDate} lockCurrency onChange={(field, value) => setValue(field, value)} /><p className="mt-3 text-xs text-muted-foreground">Payments use the purchase-invoice currency. The Bank/Cash account and journal remain in {currency}; any difference posts to Realized FX Gain/Loss.</p></section><div className="flex justify-end gap-2"><Button asChild variant="ghost"><Link href={`/b/${businessId}/purchases/invoices`}>Cancel</Link></Button><Button type="submit" disabled={isSubmitting}>{isSubmitting && <LoaderCircle className="size-4 animate-spin" />} Post Payment</Button></div></form>;
}
