"use client";

import { useState } from "react";
import Link from "next/link";
import { Ban, CircleCheck, Download, FilePlus2, MoreHorizontal, PackagePlus, Pencil, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { DialogContent, DialogDescription, DialogRoot, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { cancelPurchaseOrderAction, closePurchaseOrderAction, deletePurchaseOrderAction } from "./actions";
import type { PurchaseOrderStatus } from "./purchase-order-service";

type Confirm = "close" | "cancel" | "delete" | null;
export function PurchaseOrderViewActions({ businessId, orderId, orderNumber, status, inventoryEnabled, hasReceivableItems }: { businessId: string; orderId: string; orderNumber: string; status: PurchaseOrderStatus; inventoryEnabled: boolean; hasReceivableItems: boolean }) {
  const [confirm, setConfirm] = useState<Confirm>(null); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function run() { setPending(true); setError(""); const result = confirm === "close" ? await closePurchaseOrderAction(businessId, orderId) : confirm === "cancel" ? await cancelPurchaseOrderAction(businessId, orderId) : await deletePurchaseOrderAction(businessId, orderId); setPending(false); if (result.error) return setError(result.error); setConfirm(null); if (confirm === "delete") router.push(`/b/${businessId}/purchases/orders`); else router.refresh(); toast.success(confirm === "close" ? "Purchase order closed." : confirm === "cancel" ? "Purchase order cancelled." : "Draft purchase order deleted."); }
  const editable = status === "draft" || status === "issued";
  return <><div className="flex flex-wrap gap-2">{editable && <Button asChild><Link href={`/b/${businessId}/purchases/orders/${orderId}/edit`}><Pencil className="size-4" /> Edit</Link></Button>}{inventoryEnabled && hasReceivableItems && status !== "cancelled" && <Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/goods-receipts/new?orderId=${orderId}`}><PackagePlus className="size-4" /> Receive Goods</Link></Button>}{status !== "cancelled" && <Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/invoices/new?orderId=${orderId}`}><FilePlus2 className="size-4" /> Create Purchase Invoice</Link></Button>}<Button asChild variant="secondary" className="hidden md:inline-flex"><a href={`/api/businesses/${businessId}/documents/purchase-order/${orderId}/pdf`} target="_blank" rel="noreferrer"><Download className="size-4" /> Print / PDF</a></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="secondary">More <MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild className="md:hidden"><a href={`/api/businesses/${businessId}/documents/purchase-order/${orderId}/pdf`} target="_blank"><Download className="size-4" /> Print / PDF</a></DropdownMenuItem>{status === "issued" && <DropdownMenuItem onSelect={() => setConfirm("close")}><CircleCheck className="size-4" /> Close order</DropdownMenuItem>}{editable && <DropdownMenuItem className="text-danger focus:text-danger" onSelect={() => setConfirm("cancel")}><Ban className="size-4" /> Cancel order</DropdownMenuItem>}{status === "draft" && <><DropdownMenuSeparator /><DropdownMenuItem className="text-danger focus:text-danger" onSelect={() => setConfirm("delete")}><Trash2 className="size-4" /> Delete draft</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>
    <DialogRoot open={!!confirm} onOpenChange={(open) => !open && setConfirm(null)}><DialogContent><DialogTitle>{confirm === "close" ? `Close ${orderNumber}?` : confirm === "cancel" ? `Cancel ${orderNumber}?` : `Delete ${orderNumber}?`}</DialogTitle><DialogDescription>{confirm === "close" ? "The order remains available for history and linked bills." : confirm === "cancel" ? "The order will be retained without any ledger impact." : "This permanently removes the draft purchase order."}</DialogDescription>{error && <div role="alert" className="mt-4 rounded-md border border-danger/25 bg-danger/10 px-3 py-2 text-sm text-danger">{error}</div>}<div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => setConfirm(null)}>Keep order</Button><Button variant={confirm === "close" ? "primary" : "danger"} disabled={pending} onClick={run}>{confirm === "close" ? "Close order" : confirm === "cancel" ? "Cancel order" : "Delete draft"}</Button></div></DialogContent></DialogRoot></>;
}
