import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { requireModule } from "@/core/permissions/require-module";
import { getCustomFieldValuesForEntities, listCustomFieldDefinitions } from "@/modules/custom-fields/custom-field-service";
import { CustomerForm } from "@/modules/customers/customer-form";
import { getCustomer } from "@/modules/customers/customer-service";
import { getCurrencySettings } from "@/modules/currency/exchange-rate";
export default async function EditCustomerPage({ params }: { params: Promise<{ businessId: string; customerId: string }> }) { const { businessId, customerId } = await params; const { user } = await requireModule(businessId, "sales"); const customer = getCustomer(businessId, user.id, customerId); if (!customer) notFound(); const settings = getCurrencySettings(businessId, user.id); const customFields = listCustomFieldDefinitions(businessId, user.id, "customer").map(({ id, name, fieldType, selectOptions, isRequired }) => ({ id, name, fieldType, selectOptions, isRequired })); const customFieldValues = customFields.length ? getCustomFieldValuesForEntities(businessId, user.id, "customer", [customerId]).get(customerId) ?? {} : {}; return <div className="page-container"><Link href={`/b/${businessId}/customers/${customerId}`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> {customer.name}</Link><div className="mb-7"><h1 className="page-title">Edit Customer</h1><p className="page-description">Update contact and eInvoice delivery information without changing related documents.</p></div><CustomerForm businessId={businessId} customerId={customerId} currencies={settings.currencies.filter((currency) => currency.is_active || currency.code === customer.defaultCurrencyCode).map((currency) => ({ code: currency.code, name: currency.name }))} customFields={customFields} customFieldValues={customFieldValues} initial={{ name: customer.name, email: customer.email ?? "", phone: customer.phone ?? "", taxReference: customer.taxReference ?? "", legalName: customer.legalName ?? "", trn: customer.trn ?? "", legalRegistrationIdentifier: customer.legalRegistrationIdentifier ?? "", electronicAddress: customer.electronicAddress ?? "", electronicAddressScheme: customer.electronicAddressScheme ?? "", addressLine1: customer.addressLine1 ?? "", city: customer.city ?? "", countrySubdivision: customer.countrySubdivision ?? "", countryCode: customer.countryCode ?? "", buyerReference: customer.buyerReference ?? "", defaultCurrencyCode: customer.defaultCurrencyCode, billingAddress: customer.billingAddress ?? "", deliveryAddress: customer.deliveryAddress ?? "", isActive: customer.isActive }} /></div>; }
