import Link from "next/link";
import { ArrowLeft, Pencil } from "lucide-react";
import { notFound } from "next/navigation";
import { NoticeToast } from "@/components/notice-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireModule } from "@/core/permissions/require-module";
import { formatMoney } from "@/core/format";
import { getInventoryLocation } from "@/modules/inventory/inventory-location-service";
import { formatQuantityMicros } from "@/modules/inventory/inventory-valuation";
export default async function LocationViewPage({ params, searchParams }: { params: Promise<{ businessId: string; locationId: string }>; searchParams: Promise<{ notice?: string }> }) { const { businessId, locationId } = await params; const { notice } = await searchParams; const { user, access } = await requireModule(businessId, "inventory"); const record = getInventoryLocation(businessId, user.id, locationId); if (!record) notFound(); const l = record.location; return <div className="page-container"><NoticeToast message={notice} /><Link href={`/b/${businessId}/inventory/locations`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Inventory Locations</Link><div className="page-header"><div><div className="flex flex-wrap items-center gap-2"><h1 className="page-title">{String(l.name)}</h1>{l.is_default ? <Badge tone="info">Default</Badge> : null}<Badge tone={l.is_active ? "success" : "neutral"}>{l.is_active ? "Active" : "Inactive"}</Badge></div><p className="mt-1 tabular text-sm text-muted-foreground">{String(l.code)}{l.address ? ` · ${String(l.address)}` : ""}</p></div><Button asChild><Link href={`/b/${businessId}/inventory/locations/${locationId}/edit`}><Pencil className="size-4" /> Edit</Link></Button></div><section className="data-panel overflow-x-auto"><table className="data-table min-w-[650px]"><thead><tr><th>Item</th><th>SKU</th><th className="text-right!">Quantity</th><th className="text-right!">Value</th></tr></thead><tbody>{record.stock.length ? record.stock.map((row) => <tr key={String(row.id)}><td><Link href={`/b/${businessId}/inventory/items/${String(row.id)}`} className="font-medium text-primary hover:underline">{String(row.name)}</Link></td><td className="tabular text-muted-foreground">{String(row.sku ?? "—")}</td><td className="money text-right">{formatQuantityMicros(Number(row.quantity_micros))} {String(row.unit_name)}</td><td className="money text-right">{formatMoney(Number(row.value_minor), access.business.currency)}</td></tr>) : <tr><td colSpan={4} className="py-10 text-center text-muted-foreground">No stock at this location.</td></tr>}</tbody></table></section></div>; }
