import Link from "next/link";
import { ArrowLeft, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireModule } from "@/core/permissions/require-module";
import { formatDate, formatMoney } from "@/core/format";
import { listGoodsReceipts } from "@/modules/inventory/goods-receipt-service";
import { formatQuantityMicros } from "@/modules/inventory/inventory-valuation";
const tones = { draft: "neutral", posted: "info", void: "danger" } as const;
export default async function GoodsReceiptsPage({ params }: { params: Promise<{ businessId: string }> }) { const { businessId } = await params; const { user, access } = await requireModule(businessId, "inventory"); const rows = listGoodsReceipts(businessId, user.id); return <div className="page-container page-wide"><Link href={`/b/${businessId}/inventory/items`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Inventory</Link><div className="page-header"><div><h1 className="page-title">Goods Receipts</h1><p className="page-description">Supplier receipts change physical stock without duplicating AP accounting.</p></div><Button asChild><Link href={`/b/${businessId}/purchases/goods-receipts/new`}><Plus className="size-4" /> New Goods Receipt</Link></Button></div>{rows.length ? <div className="data-panel overflow-x-auto"><table className="data-table min-w-[800px]"><thead><tr><th>Receipt</th><th>Supplier</th><th>Date</th><th>Location</th><th className="text-right!">Quantity</th><th className="text-right!">Value</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}><td><Link href={`/b/${businessId}/purchases/goods-receipts/${String(row.id)}`} className="tabular font-medium text-primary hover:underline">{String(row.receipt_number)}</Link></td><td>{String(row.supplier_name)}</td><td>{formatDate(String(row.date))}</td><td>{String(row.location_code)}</td><td className="money text-right">{formatQuantityMicros(Number(row.quantity_micros))}</td><td className="money text-right">{formatMoney(Number(row.value_minor), access.business.currency)}</td><td><Badge tone={tones[String(row.document_status) as keyof typeof tones]}>{String(row.document_status).replace(/^./, (c) => c.toUpperCase())}</Badge></td></tr>)}</tbody></table></div> : <div className="rounded-lg border border-dashed border-border-strong bg-surface py-12 text-center"><p className="font-medium">No goods receipts yet</p><p className="mt-1 text-sm text-muted-foreground">Receive against a Purchase Order or create a direct receipt.</p><Button asChild className="mt-5"><Link href={`/b/${businessId}/purchases/goods-receipts/new`}>Create Goods Receipt</Link></Button></div>}</div>; }
