import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { requireModule } from "@/core/permissions/require-module";
import { formatDate, formatMoney } from "@/core/format";
import { listProjects } from "@/modules/projects/project-service";
import { listInventoryItems } from "@/modules/inventory/inventory-item-service";
import { listInventoryLocations } from "@/modules/inventory/inventory-location-service";
import { getInventoryMovementReport } from "@/modules/inventory/inventory-report-service";
import { formatQuantityMicros } from "@/modules/inventory/inventory-valuation";

const selectClass = "h-9 rounded-[6px] border border-border-strong bg-surface-raised px-3 text-sm text-foreground outline-none focus:border-primary focus:ring-2 focus:ring-ring/25";
const movementLabels: Record<string, string> = { goods_receipt: "Goods Receipt", delivery: "Delivery", adjustment_in: "Adjustment In", adjustment_out: "Adjustment Out", opening_balance: "Opening Balance" };
function sourceHref(businessId: string, sourceType: string, sourceId: string) { if (sourceType.startsWith("goods_receipt")) return `/b/${businessId}/purchases/goods-receipts/${sourceId}`; if (sourceType.startsWith("delivery_note")) return `/b/${businessId}/sales/delivery-notes/${sourceId}`; if (sourceType.startsWith("stock_adjustment")) return `/b/${businessId}/inventory/adjustments/${sourceId}`; return null; }

export default async function InventoryMovementPage({ params, searchParams }: { params: Promise<{ businessId: string }>; searchParams: Promise<{ dateFrom?: string; dateTo?: string; itemId?: string; locationId?: string; movementType?: string; projectId?: string }> }) {
  const { businessId } = await params; const filters = await searchParams;
  const { user, access } = await requireModule(businessId, "reports");
  if (!access.modules.includes("inventory")) redirect(`/b/${businessId}/forbidden?module=inventory`);
  const items = listInventoryItems(businessId, user.id); const locations = listInventoryLocations(businessId, user.id); const projects = listProjects(businessId, user.id);
  const rows = getInventoryMovementReport(businessId, user.id, filters);
  return <div className="page-container"><Link href={`/b/${businessId}/reports`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Reports</Link><div className="page-header"><div><h1 className="page-title">Inventory Movement</h1><p className="page-description">Auditable movement ledger with running quantity by item and location.</p></div></div>
    <form className="mb-4 flex flex-wrap items-end gap-3 rounded-lg border border-border bg-surface p-3"><label className="space-y-1 text-xs text-muted-foreground">Date from<Input name="dateFrom" type="date" defaultValue={filters.dateFrom} className="mt-1 w-40 text-foreground" /></label><label className="space-y-1 text-xs text-muted-foreground">Date to<Input name="dateTo" type="date" defaultValue={filters.dateTo} className="mt-1 w-40 text-foreground" /></label><label className="space-y-1 text-xs text-muted-foreground">Item<select name="itemId" defaultValue={filters.itemId ?? ""} className={`${selectClass} mt-1 block min-w-52`}><option value="">All items</option>{items.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.sku ?? "No SKU")} · {String(item.name)}</option>)}</select></label><label className="space-y-1 text-xs text-muted-foreground">Location<select name="locationId" defaultValue={filters.locationId ?? ""} className={`${selectClass} mt-1 block min-w-44`}><option value="">All locations</option>{locations.map((location) => <option key={String(location.id)} value={String(location.id)}>{String(location.code)}</option>)}</select></label><label className="space-y-1 text-xs text-muted-foreground">Type<select name="movementType" defaultValue={filters.movementType ?? ""} className={`${selectClass} mt-1 block min-w-44`}><option value="">All types</option>{Object.entries(movementLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="space-y-1 text-xs text-muted-foreground">Project<select name="projectId" defaultValue={filters.projectId ?? ""} className={`${selectClass} mt-1 block min-w-48`}><option value="">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></label><Button type="submit" variant="secondary">Apply</Button></form>
    {rows.length ? <div className="data-panel overflow-x-auto"><table className="data-table min-w-[1120px]"><thead><tr><th>Date</th><th>Item</th><th>Type</th><th>Reference</th><th>Location</th><th className="text-right!">Qty In</th><th className="text-right!">Qty Out</th><th className="text-right!">Running Qty</th><th className="text-right!">Value</th><th>Project</th></tr></thead><tbody>{rows.map((row) => { const quantity = Number(row.quantity_delta_micros); const href = sourceHref(businessId, String(row.source_type), String(row.source_id)); return <tr key={String(row.id)}><td>{formatDate(String(row.date))}</td><td><Link href={`/b/${businessId}/inventory/items/${String(row.item_id)}`} className="font-medium text-primary hover:underline">{String(row.item_name)}</Link><span className="ml-1 text-xs text-muted-foreground">{String(row.unit_name)}</span></td><td>{movementLabels[String(row.movement_type)] ?? String(row.movement_type)}</td><td>{href ? <Link href={href} className="tabular font-medium text-primary hover:underline">{String(row.description ?? row.source_id)}</Link> : String(row.description ?? "—")}</td><td>{String(row.location_code)}</td><td className="money text-right">{quantity > 0 ? formatQuantityMicros(quantity) : "—"}</td><td className="money text-right">{quantity < 0 ? formatQuantityMicros(-quantity) : "—"}</td><td className="money text-right font-medium">{formatQuantityMicros(Number(row.running_quantity_micros))}</td><td className="money text-right">{formatMoney(Number(row.value_delta_minor), access.business.currency)}</td><td>{row.project_name ? `${String(row.project_code)} · ${String(row.project_name)}` : "—"}</td></tr>; })}</tbody></table></div> : <div className="rounded-lg border border-border bg-surface py-10 text-center"><p className="font-medium">No inventory movement matches these filters</p><p className="mt-1 text-sm text-muted-foreground">Posted receipts, deliveries, and adjustments appear here.</p></div>}
  </div>;
}
