"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { Download, FileUp, LoaderCircle, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { DialogClose, DialogContent, DialogDescription, DialogRoot, DialogTitle } from "@/components/ui/dialog";
import { formatDate } from "@/core/format";
import { addProjectNoteAction, deleteProjectAttachmentAction, deleteProjectNoteAction, uploadProjectAttachmentAction } from "./actions";

type Note = { id: string; body: string; created_at: string };
type Attachment = { id: string; original_name: string; mime_type: string; size_bytes: number; created_at: string };
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }

export function ProjectNotes({ businessId, projectId, notes }: { businessId: string; projectId: string; notes: Note[] }) {
  const [body, setBody] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  async function add() { setPending(true); setError(""); const result = await addProjectNoteAction(businessId, projectId, { body }); setPending(false); if (result.error) return setError(result.error); setBody(""); toast.success("Project note added."); router.refresh(); }
  async function remove(noteId: string) { const result = await deleteProjectNoteAction(businessId, projectId, noteId); if (result.error) return toast.error(result.error); toast.success("Project note deleted."); router.refresh(); }
  return <div className="space-y-4"><div><label htmlFor="project-note" className="text-[13px] font-medium">Add a note</label><textarea id="project-note" rows={3} value={body} onChange={(event) => setBody(event.target.value)} className="mt-1.5 w-full rounded-md border border-border-strong bg-surface-raised px-3 py-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-ring/25" placeholder="Record a concise project update…" />{error && <p role="alert" className="field-error">{error}</p>}<div className="mt-2 flex justify-end"><Button size="sm" onClick={add} disabled={pending || !body.trim()}>{pending && <LoaderCircle className="size-4 animate-spin" />} Add Note</Button></div></div>{notes.length ? <div className="divide-y divide-border border-y border-border">{notes.map((note) => <article key={note.id} className="group py-3"><div className="flex items-start justify-between gap-3"><div><p className="whitespace-pre-wrap text-sm leading-6">{note.body}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(note.created_at)}</p></div><Button variant="ghost" size="icon" aria-label="Delete project note" onClick={() => remove(note.id)}><Trash2 className="size-4 text-muted-foreground" /></Button></div></article>)}</div> : <p className="text-sm text-muted-foreground">No project notes yet.</p>}</div>;
}

export function ProjectFiles({ businessId, projectId, attachments }: { businessId: string; projectId: string; attachments: Attachment[] }) {
  const inputRef = useRef<HTMLInputElement>(null); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [deleteId, setDeleteId] = useState<string | null>(null); const router = useRouter();
  async function upload() { const file = inputRef.current?.files?.[0]; if (!file) return setError("Choose a file to upload."); setPending(true); setError(""); const form = new FormData(); form.set("file", file); const result = await uploadProjectAttachmentAction(businessId, projectId, form); setPending(false); if (result.error) return setError(result.error); if (inputRef.current) inputRef.current.value = ""; toast.success("Attachment uploaded."); router.refresh(); }
  async function remove() { if (!deleteId) return; setPending(true); const result = await deleteProjectAttachmentAction(businessId, projectId, deleteId); setPending(false); if (result.error) return setError(result.error); setDeleteId(null); toast.success("Attachment deleted."); router.refresh(); }
  return <><div className="space-y-4"><div className="flex flex-wrap items-end gap-2"><label className="min-w-[240px] flex-1 text-[13px] font-medium">Upload file<input ref={inputRef} type="file" className="mt-1.5 block w-full text-sm file:mr-3 file:h-9 file:rounded-md file:border file:border-border-strong file:bg-surface-raised file:px-3 file:text-sm file:font-medium" /></label><Button variant="secondary" onClick={upload} disabled={pending}><FileUp className="size-4" /> Upload</Button></div>{error && <p role="alert" className="field-error">{error}</p>}{attachments.length ? <div className="data-panel overflow-x-auto"><table className="data-table min-w-[620px]"><thead><tr><th>File</th><th>Type</th><th>Size</th><th>Uploaded</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{attachments.map((file) => <tr key={file.id}><td><Link className="inline-flex items-center gap-2 font-medium text-primary hover:underline" href={`/api/businesses/${businessId}/projects/attachments/${file.id}`}><Download className="size-4" />{file.original_name}</Link></td><td className="text-muted-foreground">{file.mime_type}</td><td className="tabular">{formatBytes(file.size_bytes)}</td><td>{formatDate(file.created_at)}</td><td className="text-right"><Button variant="ghost" size="icon" aria-label={`Delete ${file.original_name}`} onClick={() => setDeleteId(file.id)}><Trash2 className="size-4 text-muted-foreground" /></Button></td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">No files attached to this project.</p>}</div><DialogRoot open={Boolean(deleteId)} onOpenChange={(open) => !open && setDeleteId(null)}><DialogContent><DialogTitle>Delete attachment?</DialogTitle><DialogDescription>The file will be removed from this business and cannot be recovered unless it exists in a backup.</DialogDescription><div className="mt-5 flex justify-end gap-2"><DialogClose asChild><Button variant="secondary" disabled={pending}>Cancel</Button></DialogClose><Button variant="danger" disabled={pending} onClick={remove}>{pending ? "Deleting…" : "Delete File"}</Button></div></DialogContent></DialogRoot></>;
}
