import type { DocumentTemplate } from "./pdf-engine";

const textBase = {
  type: "text",
  height: 8,
  fontSize: 11,
  lineHeight: 1.2,
  fontColor: "#253247",
  backgroundColor: "",
  opacity: 1,
  rotate: 0,
  alignment: "left",
  verticalAlignment: "middle",
  characterSpacing: 0,
  required: false,
  readOnly: false,
};

export const defaultInvoiceTemplate = {
  basePdf: { width: 210, height: 297, padding: [16, 16, 18, 16] },
  schemas: [[
    { ...textBase, name: "companyName", content: "Northstar Technical Services LLC", position: { x: 18, y: 18 }, width: 104, height: 10, fontSize: 16 },
    { ...textBase, name: "invoiceTitle", content: "INVOICE", position: { x: 146, y: 18 }, width: 46, height: 10, fontSize: 18, alignment: "right" },
    { ...textBase, name: "invoiceNumber", content: "INV-0001", position: { x: 146, y: 30 }, width: 46, alignment: "right" },
    { ...textBase, name: "customerLabel", content: "BILL TO", position: { x: 18, y: 50 }, width: 45, height: 6, fontSize: 8, fontColor: "#68758a" },
    { ...textBase, name: "customerName", content: "Emberline Trading LLC", position: { x: 18, y: 57 }, width: 92, height: 12, fontSize: 12 },
    { ...textBase, name: "invoiceDate", content: "Invoice date: 08 Aug 2026", position: { x: 125, y: 50 }, width: 67, alignment: "right" },
    { ...textBase, name: "dueDate", content: "Due date: 22 Aug 2026", position: { x: 125, y: 59 }, width: 67, alignment: "right" },
    {
      name: "itemsTable",
      type: "table",
      position: { x: 18, y: 82 },
      width: 174,
      height: 68,
      content: JSON.stringify([["Site assessment", "1", "2,800.00", "2,800.00"]]),
      showHead: true,
      head: ["Description", "Qty", "Rate", "Amount"],
      headWidthPercentages: [52, 10, 18, 20],
      tableStyles: { borderWidth: 0.2, borderColor: "#cbd4df" },
      headStyles: {
        alignment: "left",
        verticalAlignment: "middle",
        fontSize: 9,
        lineHeight: 1.2,
        characterSpacing: 0,
        fontColor: "#42516a",
        backgroundColor: "#edf1f5",
        borderColor: "#cbd4df",
        borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
        padding: { top: 3, right: 3, bottom: 3, left: 3 },
      },
      bodyStyles: {
        alignment: "left",
        verticalAlignment: "middle",
        fontSize: 9,
        lineHeight: 1.2,
        characterSpacing: 0,
        fontColor: "#253247",
        backgroundColor: "",
        alternateBackgroundColor: "#f8fafc",
        borderColor: "#dce2e9",
        borderWidth: { top: 0.15, right: 0.15, bottom: 0.15, left: 0.15 },
        padding: { top: 3, right: 3, bottom: 3, left: 3 },
      },
      columnStyles: { alignment: { 1: "right", 2: "right", 3: "right" } },
      required: false,
      readOnly: false,
    },
    { ...textBase, name: "subtotal", content: "Subtotal    AED 5,700.00", position: { x: 122, y: 166 }, width: 70, alignment: "right" },
    { ...textBase, name: "vat", content: "VAT             AED 285.00", position: { x: 122, y: 176 }, width: 70, alignment: "right" },
    { ...textBase, name: "total", content: "TOTAL        AED 5,985.00", position: { x: 122, y: 187 }, width: 70, height: 10, alignment: "right", fontSize: 13 },
  ]],
  pdfmeVersion: "5.5.10",
} as DocumentTemplate;

export function sampleInvoiceInput(long = false) {
  const rows = Array.from({ length: long ? 42 : 4 }, (_, index) => [
    long ? `Service line ${index + 1} — detailed technical work and site support` : ["Site inspection", "Preventive maintenance", "Replacement parts", "Call-out support"][index],
    String((index % 3) + 1),
    `${(450 + index * 35).toFixed(2)}`,
    `${(((index % 3) + 1) * (450 + index * 35)).toFixed(2)}`,
  ]);
  return {
    companyName: "Northstar Technical Services LLC",
    invoiceTitle: "INVOICE",
    invoiceNumber: long ? "INV-LONG-PREVIEW" : "INV-0001",
    customerLabel: "BILL TO",
    customerName: "Emberline Trading LLC",
    invoiceDate: "Invoice date: 08 Aug 2026",
    dueDate: "Due date: 22 Aug 2026",
    itemsTable: JSON.stringify(rows),
    subtotal: "Subtotal    AED 5,700.00",
    vat: "VAT             AED 285.00",
    total: "TOTAL        AED 5,985.00",
  };
}
