import Link from "next/link";
import { ArrowLeft, CircleDollarSign, FilePlus2, Mail, Pencil, Phone, ScrollText, ShoppingCart } from "lucide-react";
import { notFound } from "next/navigation";
import { NoticeToast } from "@/components/notice-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireModule } from "@/core/permissions/require-module";
import { formatDate, formatMoney } from "@/core/format";
import { listPurchaseInvoices } from "@/modules/purchase-invoices/purchase-invoice-service";
import { listPurchaseOrders } from "@/modules/purchase-orders/purchase-order-service";
import { getSupplierAccountingSummary } from "@/modules/reports/supplier-statement-service";
import { listSupplierPayments } from "@/modules/supplier-payments/supplier-payment-service";
import { getSupplier } from "@/modules/suppliers/supplier-service";

export default async function SupplierPage({ params, searchParams }: { params: Promise<{ businessId: string; supplierId: string }>; searchParams: Promise<{ notice?: string }> }) { const { businessId, supplierId } = await params; const { notice } = await searchParams; const { user, access } = await requireModule(businessId, "purchases"); const supplier = getSupplier(businessId, user.id, supplierId); if (!supplier) notFound(); const orders = listPurchaseOrders(businessId, user.id, supplierId); const invoices = listPurchaseInvoices(businessId, user.id, supplierId); const payments = listSupplierPayments(businessId, user.id, supplierId); const summary = getSupplierAccountingSummary(businessId, user.id, supplierId); const currency = access.business.currency; return <div className="page-container page-wide"><NoticeToast message={notice} /><Link href={`/b/${businessId}/suppliers`} className="mb-5 inline-flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Suppliers</Link><div className="page-header"><div><div className="flex items-center gap-2"><h1 className="page-title">{supplier.name}</h1><Badge tone={supplier.isActive ? "success" : "neutral"}>{supplier.isActive ? "Active" : "Inactive"}</Badge></div><p className="page-description">Supplier · Added {formatDate(supplier.createdAt.slice(0, 10))}</p></div><div className="flex flex-wrap gap-2"><Button asChild><Link href={`/b/${businessId}/suppliers/${supplierId}/edit`}><Pencil className="size-4" /> Edit</Link></Button><Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/orders/new?supplierId=${supplierId}`}><ShoppingCart className="size-4" /> New Purchase Order</Link></Button><Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/invoices/new?supplierId=${supplierId}`}><FilePlus2 className="size-4" /> New Purchase Invoice</Link></Button>{summary.outstandingMinor > 0 && <Button asChild variant="secondary"><Link href={`/b/${businessId}/purchases/payments/new?supplierId=${supplierId}`}><CircleDollarSign className="size-4" /> Record Payment</Link></Button>}<Button asChild variant="secondary"><Link href={`/b/${businessId}/reports/supplier-statement?supplierId=${supplierId}`}><ScrollText className="size-4" /> Statement</Link></Button></div></div>
  <section aria-label="Supplier accounting summary" className="mb-5 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-3"><div className="bg-surface-raised px-4 py-3"><p className="text-xs text-muted-foreground">Outstanding Payable · Base</p><p className="money mt-1 text-base font-semibold">{formatMoney(summary.outstandingMinor, currency)}</p></div><div className="bg-surface-raised px-4 py-3"><p className="text-xs text-muted-foreground">Total Purchased · Base</p><p className="money mt-1 text-base font-semibold">{formatMoney(summary.totalPurchasedMinor, currency)}</p></div><div className="bg-surface-raised px-4 py-3"><p className="text-xs text-muted-foreground">Carrying Released · Base</p><p className="money mt-1 text-base font-semibold">{formatMoney(summary.totalPaidMinor, currency)}</p></div></section>
  <div className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]"><section className="rounded-lg border border-border bg-surface-raised p-5"><h2 className="text-base font-semibold">Contact details</h2><dl className="mt-4 space-y-4"><div><dt className="text-xs text-muted-foreground">Email</dt><dd className="mt-1 flex items-center gap-2"><Mail className="size-4 text-muted-foreground" />{supplier.email || "Not provided"}</dd></div><div><dt className="text-xs text-muted-foreground">Phone</dt><dd className="mt-1 flex items-center gap-2"><Phone className="size-4 text-muted-foreground" />{supplier.phone || "Not provided"}</dd></div><div><dt className="text-xs text-muted-foreground">TRN / reference</dt><dd className="mt-1 tabular">{supplier.taxReference || "Not provided"}</dd></div><div><dt className="text-xs text-muted-foreground">Address</dt><dd className="mt-1 text-sm">{supplier.address || "Not provided"}</dd></div></dl></section><section className="data-panel"><div className="flex h-12 items-center border-b border-border px-4"><h2 className="font-semibold">Recent Purchase Invoices</h2></div>{invoices.length ? <div className="overflow-x-auto"><table className="data-table min-w-[680px]"><thead><tr><th>Bill</th><th>Date</th><th className="text-right!">Total</th><th className="text-right!">Balance</th><th>Status</th></tr></thead><tbody>{invoices.slice(0, 8).map((invoice) => <tr key={invoice.id}><td><Link href={`/b/${businessId}/purchases/invoices/${invoice.id}`} className="tabular font-medium text-primary hover:underline">{invoice.internal_number}</Link></td><td>{formatDate(invoice.invoice_date)}</td><td className="money text-right">{formatMoney(invoice.total_minor, invoice.currency_code, invoice.currency_minor_unit)}</td><td className="money text-right">{invoice.document_status === "posted" ? formatMoney(invoice.balanceMinor, invoice.currency_code, invoice.currency_minor_unit) : "—"}</td><td><Badge tone={invoice.document_status === "posted" ? "info" : invoice.document_status === "void" ? "danger" : "neutral"}>{invoice.document_status}</Badge></td></tr>)}</tbody></table></div> : <div className="p-8 text-center text-sm text-muted-foreground">No purchase invoices yet.</div>}</section></div>
  <section className="data-panel mt-5"><div className="flex h-12 items-center border-b border-border px-4"><h2 className="font-semibold">Recent Purchase Orders</h2></div>{orders.length ? <div className="overflow-x-auto"><table className="data-table min-w-[620px]"><thead><tr><th>Order</th><th>Date</th><th className="text-right!">Total</th><th>Status</th></tr></thead><tbody>{orders.slice(0, 8).map((order) => <tr key={order.id}><td><Link href={`/b/${businessId}/purchases/orders/${order.id}`} className="tabular font-medium text-primary hover:underline">{order.order_number}</Link></td><td>{formatDate(order.date)}</td><td className="money text-right">{formatMoney(order.total_minor, order.currency_code, order.currency_minor_unit)}</td><td className="capitalize">{order.status}</td></tr>)}</tbody></table></div> : <div className="p-7 text-center text-sm text-muted-foreground">No purchase orders yet.</div>}</section>
  <section className="data-panel mt-5"><div className="flex h-12 items-center border-b border-border px-4"><h2 className="font-semibold">Recent Payments</h2></div>{payments.length ? <div className="overflow-x-auto"><table className="data-table min-w-[650px]"><thead><tr><th>Payment</th><th>Date</th><th>Invoice</th><th>Reference</th><th className="text-right!">Amount</th></tr></thead><tbody>{payments.slice(0, 8).map((payment) => <tr key={payment.id}><td><Link href={`/b/${businessId}/purchases/payments/${payment.id}`} className="tabular font-medium text-primary hover:underline">{payment.payment_number}</Link></td><td>{formatDate(payment.date)}</td><td><Link href={`/b/${businessId}/purchases/invoices/${payment.invoice_id}`} className="tabular text-primary hover:underline">{payment.internal_number}</Link></td><td className="text-muted-foreground">{payment.reference || "—"}</td><td className="money text-right">{formatMoney(payment.amount_minor, payment.currency_code, payment.currency_minor_unit)}</td></tr>)}</tbody></table></div> : <div className="p-7 text-center text-sm text-muted-foreground">No supplier payments yet.</div>}</section>
  </div>; }
